<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SpawnData extends Seeder
	{
		/**
		* Run the database seeds.
		*
		* @return void
		*/
		public function run()
		{

		DB::table('creature_groups')->insert([
			['name' => 'Shillatown', 'description' => "Shillatown Guards", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Beach', 'description' => "Beach creatures", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Outskirts', 'description' => "Outskirts creatures", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Sewers', 'description' => "Sewers creatures", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Vast Valley', 'description' => "Vast Valley creatures", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Druid Valley', 'description' => "Druid Valley creatures", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Cemetary', 'description' => "Cemetary creatures", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Crypt', 'description' => "Crypt creatures", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Lake Gala', 'description' => "Lake Gala creatures", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Dark Forest', 'description' => "Dark Forest creatures", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Mountains', 'description' => "Mountains creatures", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Ogre Cave', 'description' => "Ogre Cave creatures", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Deep Dark Forest', 'description' => "Deep Dark Forest creatures", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'The Pit', 'description' => "Pit creatures", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Outer Maze', 'description' => "Outer Maze creatures", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Inner Maze Group 1', 'description' => "Inner Maze creatures", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Inner Maze Group 2', 'description' => "Inner Maze creatures", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Inner Maze Group 3', 'description' => "Inner Maze creatures", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Inner Maze Group 4', 'description' => "Inner Maze creatures", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Inner Maze Group 5', 'description' => "Inner Maze creatures", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Dungeons - Cells', 'description' => "Dungeon Cell creatures", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Dungeons', 'description' => "Dungeons creatures", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Sky Castle Level 1', 'description' => "Sky Castle creatures", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Sky Castle Level 2', 'description' => "Sky Castle creatures", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Sky Castle Level 3', 'description' => "Sky Castle creatures", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Great Plains Group 1', 'description' => "Great Plains creatures", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Great Plains Group 2', 'description' => "Great Plains creatures", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Great Plains Group 3', 'description' => "Great Plains creatures", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Great Plains Group Salena', 'description' => "Great Plains creatures", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Volcano Ridge', 'description' => "", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Upper Volcano Level -1', 'description' => "", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Upper Volcano -2', 'description' => "", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Lower Volcano 0 (3)', 'description' => "", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Lower Volcano -1 (4)', 'description' => "", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Lower Volcano -2 (5)', 'description' => "", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Lower Volcano -3 (6)', 'description' => "", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Lower Volcano -4 (7)', 'description' => "", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Lower Volcano -5 (8)', 'description' => "", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Canals Creatures 1', 'description' => "Middle Group", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Canals Creatures 2', 'description' => "Canals Northern Group", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Canals Creatures 3', 'description' => "Canals Southern Group", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Clouds Creature Group', 'description' => "", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Vast Desert Group 1', 'description' => "Easy Group", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Vast Desert Group 2', 'description' => "Medium Group", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Vast Desert Group 3', 'description' => "Hard Group", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Elven Village Guards', 'description' => "", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Halfling Village Guards', 'description' => "", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Dwarf Village Guards', 'description' => "", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Orc Village Guards', 'description' => "", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Necropolis Village Guards', 'description' => "", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Draconian Lair Guards', 'description' => "", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Ocean Surface (0)', 'description' => "", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Ocean 1st Fathom (-1)', 'description' => "", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Ocean 2nd Fathom (-2)', 'description' => "", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Ocean 3rd Fathom (-3)', 'description' => "", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Ocean 4th Fathom (-4)', 'description' => "", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Ocean 5th Fathom (-5)', 'description' => "", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Underground River', 'description' => "", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Glacier Test [DELETE]', 'description' => "", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Atlantis Test [DELETE]', 'description' => "", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Ice Palace Test [DELETE]', 'description' => "", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Catacombs Test [DELETE]', 'description' => "", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Pyramid Test [DELETE]', 'description' => "", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Sand Mansion Test [DELETE]', 'description' => "", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			]);

		DB::table('creature_to_creature_groups')->insert([
			['creatures_id' => 1, 'creature_groups_id' => 1, 'weight' => 100, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 2, 'creature_groups_id' => 2, 'weight' => 30, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 3, 'creature_groups_id' => 2, 'weight' => 30, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 4, 'creature_groups_id' => 2, 'weight' => 40, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 6, 'creature_groups_id' => 3, 'weight' => 30, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 7, 'creature_groups_id' => 3, 'weight' => 30, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 8, 'creature_groups_id' => 3, 'weight' => 20, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 9, 'creature_groups_id' => 3, 'weight' => 20, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 10, 'creature_groups_id' => 4, 'weight' => 55, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 11, 'creature_groups_id' => 4, 'weight' => 45, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 12, 'creature_groups_id' => 5, 'weight' => 55, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 13, 'creature_groups_id' => 5, 'weight' => 45, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 14, 'creature_groups_id' => 6, 'weight' => 30, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 15, 'creature_groups_id' => 6, 'weight' => 35, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 16, 'creature_groups_id' => 6, 'weight' => 35, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 18, 'creature_groups_id' => 7, 'weight' => 20, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 19, 'creature_groups_id' => 7, 'weight' => 20, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 20, 'creature_groups_id' => 7, 'weight' => 20, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 21, 'creature_groups_id' => 7, 'weight' => 20, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 22, 'creature_groups_id' => 7, 'weight' => 20, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 28, 'creature_groups_id' => 9, 'weight' => 25, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 29, 'creature_groups_id' => 9, 'weight' => 25, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 30, 'creature_groups_id' => 9, 'weight' => 25, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 31, 'creature_groups_id' => 9, 'weight' => 25, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 33, 'creature_groups_id' => 10, 'weight' => 40, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 34, 'creature_groups_id' => 10, 'weight' => 30, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 35, 'creature_groups_id' => 10, 'weight' => 30, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 37, 'creature_groups_id' => 11, 'weight' => 25, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 38, 'creature_groups_id' => 11, 'weight' => 25, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 39, 'creature_groups_id' => 11, 'weight' => 25, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 40, 'creature_groups_id' => 11, 'weight' => 25, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 42, 'creature_groups_id' => 12, 'weight' => 40, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 43, 'creature_groups_id' => 12, 'weight' => 30, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 44, 'creature_groups_id' => 12, 'weight' => 30, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 45, 'creature_groups_id' => 13, 'weight' => 20, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 46, 'creature_groups_id' => 13, 'weight' => 20, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 47, 'creature_groups_id' => 13, 'weight' => 20, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 48, 'creature_groups_id' => 13, 'weight' => 20, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 49, 'creature_groups_id' => 13, 'weight' => 20, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 50, 'creature_groups_id' => 14, 'weight' => 25, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 51, 'creature_groups_id' => 14, 'weight' => 25, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 52, 'creature_groups_id' => 14, 'weight' => 25, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 53, 'creature_groups_id' => 14, 'weight' => 25, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 2, 'creature_groups_id' => 15, 'weight' => 25, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 44, 'creature_groups_id' => 15, 'weight' => 25, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 55, 'creature_groups_id' => 16, 'weight' => 25, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 55, 'creature_groups_id' => 17, 'weight' => 25, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 55, 'creature_groups_id' => 18, 'weight' => 25, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 55, 'creature_groups_id' => 19, 'weight' => 25, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 55, 'creature_groups_id' => 20, 'weight' => 25, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 75, 'creature_groups_id' => 21, 'weight' => 25, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 77, 'creature_groups_id' => 21, 'weight' => 25, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 79, 'creature_groups_id' => 21, 'weight' => 25, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 74, 'creature_groups_id' => 22, 'weight' => 25, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 76, 'creature_groups_id' => 22, 'weight' => 25, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 78, 'creature_groups_id' => 22, 'weight' => 25, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 86, 'creature_groups_id' => 23, 'weight' => 50, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 87, 'creature_groups_id' => 23, 'weight' => 50, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 87, 'creature_groups_id' => 24, 'weight' => 30, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 88, 'creature_groups_id' => 24, 'weight' => 40, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 89, 'creature_groups_id' => 24, 'weight' => 30, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 89, 'creature_groups_id' => 25, 'weight' => 50, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 90, 'creature_groups_id' => 25, 'weight' => 50, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 93, 'creature_groups_id' => 26, 'weight' => 40, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 94, 'creature_groups_id' => 26, 'weight' => 30, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 95, 'creature_groups_id' => 26, 'weight' => 30, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 99, 'creature_groups_id' => 27, 'weight' => 40, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 100, 'creature_groups_id' => 27, 'weight' => 30, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 101, 'creature_groups_id' => 27, 'weight' => 30, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 96, 'creature_groups_id' => 28, 'weight' => 40, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 97, 'creature_groups_id' => 28, 'weight' => 30, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 98, 'creature_groups_id' => 28, 'weight' => 30, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 95, 'creature_groups_id' => 29, 'weight' => 35, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 96, 'creature_groups_id' => 29, 'weight' => 30, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 101, 'creature_groups_id' => 29, 'weight' => 30, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 103, 'creature_groups_id' => 29, 'weight' => 5, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 104, 'creature_groups_id' => 30, 'weight' => 30, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 105, 'creature_groups_id' => 30, 'weight' => 35, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 106, 'creature_groups_id' => 30, 'weight' => 35, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 107, 'creature_groups_id' => 31, 'weight' => 35, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 108, 'creature_groups_id' => 31, 'weight' => 30, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 109, 'creature_groups_id' => 31, 'weight' => 35, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 110, 'creature_groups_id' => 32, 'weight' => 35, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 111, 'creature_groups_id' => 32, 'weight' => 35, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 112, 'creature_groups_id' => 32, 'weight' => 30, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 110, 'creature_groups_id' => 33, 'weight' => 30, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 111, 'creature_groups_id' => 33, 'weight' => 30, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 113, 'creature_groups_id' => 33, 'weight' => 40, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 114, 'creature_groups_id' => 34, 'weight' => 55, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 115, 'creature_groups_id' => 34, 'weight' => 45, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 114, 'creature_groups_id' => 35, 'weight' => 30, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 116, 'creature_groups_id' => 35, 'weight' => 35, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 117, 'creature_groups_id' => 35, 'weight' => 35, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 114, 'creature_groups_id' => 36, 'weight' => 25, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 117, 'creature_groups_id' => 36, 'weight' => 45, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 118, 'creature_groups_id' => 36, 'weight' => 35, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 118, 'creature_groups_id' => 37, 'weight' => 30, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 119, 'creature_groups_id' => 37, 'weight' => 35, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 120, 'creature_groups_id' => 37, 'weight' => 35, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 120, 'creature_groups_id' => 38, 'weight' => 30, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 121, 'creature_groups_id' => 38, 'weight' => 35, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 122, 'creature_groups_id' => 38, 'weight' => 35, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 128, 'creature_groups_id' => 39, 'weight' => 20, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 125, 'creature_groups_id' => 39, 'weight' => 40, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 124, 'creature_groups_id' => 39, 'weight' => 40, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 128, 'creature_groups_id' => 40, 'weight' => 20, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 125, 'creature_groups_id' => 40, 'weight' => 40, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 127, 'creature_groups_id' => 40, 'weight' => 40, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 128, 'creature_groups_id' => 41, 'weight' => 20, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 125, 'creature_groups_id' => 41, 'weight' => 40, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 126, 'creature_groups_id' => 41, 'weight' => 40, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 129, 'creature_groups_id' => 42, 'weight' => 35, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 130, 'creature_groups_id' => 42, 'weight' => 35, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 131, 'creature_groups_id' => 42, 'weight' => 30, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 133, 'creature_groups_id' => 43, 'weight' => 35, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 134, 'creature_groups_id' => 43, 'weight' => 35, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 135, 'creature_groups_id' => 43, 'weight' => 30, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 136, 'creature_groups_id' => 44, 'weight' => 35, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 137, 'creature_groups_id' => 44, 'weight' => 35, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 138, 'creature_groups_id' => 44, 'weight' => 30, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 139, 'creature_groups_id' => 45, 'weight' => 35, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 140, 'creature_groups_id' => 45, 'weight' => 35, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 141, 'creature_groups_id' => 45, 'weight' => 30, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 142, 'creature_groups_id' => 46, 'weight' => 50, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 143, 'creature_groups_id' => 46, 'weight' => 50, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 144, 'creature_groups_id' => 47, 'weight' => 100, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 145, 'creature_groups_id' => 48, 'weight' => 100, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 151, 'creature_groups_id' => 49, 'weight' => 100, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 149, 'creature_groups_id' => 50, 'weight' => 100, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 147, 'creature_groups_id' => 51, 'weight' => 60, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 148, 'creature_groups_id' => 51, 'weight' => 40, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 154, 'creature_groups_id' => 52, 'weight' => 35, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 155, 'creature_groups_id' => 52, 'weight' => 35, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 156, 'creature_groups_id' => 52, 'weight' => 30, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 157, 'creature_groups_id' => 53, 'weight' => 35, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 158, 'creature_groups_id' => 53, 'weight' => 35, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 159, 'creature_groups_id' => 53, 'weight' => 30, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 160, 'creature_groups_id' => 54, 'weight' => 35, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 161, 'creature_groups_id' => 54, 'weight' => 35, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 162, 'creature_groups_id' => 54, 'weight' => 30, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 163, 'creature_groups_id' => 55, 'weight' => 35, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 164, 'creature_groups_id' => 55, 'weight' => 35, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 166, 'creature_groups_id' => 55, 'weight' => 30, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 167, 'creature_groups_id' => 56, 'weight' => 30, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 168, 'creature_groups_id' => 56, 'weight' => 30, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 169, 'creature_groups_id' => 56, 'weight' => 20, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 170, 'creature_groups_id' => 56, 'weight' => 20, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 171, 'creature_groups_id' => 57, 'weight' => 35, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 172, 'creature_groups_id' => 57, 'weight' => 35, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 173, 'creature_groups_id' => 57, 'weight' => 30, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 165, 'creature_groups_id' => 58, 'weight' => 100, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 174, 'creature_groups_id' => 59, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 175, 'creature_groups_id' => 59, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 176, 'creature_groups_id' => 59, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 177, 'creature_groups_id' => 59, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 178, 'creature_groups_id' => 59, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 179, 'creature_groups_id' => 59, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 180, 'creature_groups_id' => 59, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 181, 'creature_groups_id' => 59, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 182, 'creature_groups_id' => 59, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 183, 'creature_groups_id' => 59, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 184, 'creature_groups_id' => 59, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 185, 'creature_groups_id' => 59, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 186, 'creature_groups_id' => 59, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 187, 'creature_groups_id' => 59, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 188, 'creature_groups_id' => 59, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 189, 'creature_groups_id' => 59, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 190, 'creature_groups_id' => 59, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 191, 'creature_groups_id' => 59, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 192, 'creature_groups_id' => 59, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 193, 'creature_groups_id' => 59, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 194, 'creature_groups_id' => 60, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 195, 'creature_groups_id' => 60, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 196, 'creature_groups_id' => 60, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 197, 'creature_groups_id' => 60, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 198, 'creature_groups_id' => 60, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 199, 'creature_groups_id' => 60, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 200, 'creature_groups_id' => 60, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 201, 'creature_groups_id' => 60, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 202, 'creature_groups_id' => 60, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 203, 'creature_groups_id' => 60, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 205, 'creature_groups_id' => 61, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 206, 'creature_groups_id' => 61, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 207, 'creature_groups_id' => 61, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 208, 'creature_groups_id' => 61, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 209, 'creature_groups_id' => 61, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 210, 'creature_groups_id' => 61, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 211, 'creature_groups_id' => 61, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 212, 'creature_groups_id' => 61, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 213, 'creature_groups_id' => 61, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 214, 'creature_groups_id' => 61, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 215, 'creature_groups_id' => 61, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 216, 'creature_groups_id' => 62, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 217, 'creature_groups_id' => 62, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 218, 'creature_groups_id' => 62, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 219, 'creature_groups_id' => 62, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 220, 'creature_groups_id' => 62, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 221, 'creature_groups_id' => 62, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 222, 'creature_groups_id' => 62, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 223, 'creature_groups_id' => 63, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 224, 'creature_groups_id' => 63, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 225, 'creature_groups_id' => 63, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 226, 'creature_groups_id' => 63, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 227, 'creature_groups_id' => 63, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 228, 'creature_groups_id' => 63, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 229, 'creature_groups_id' => 63, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 230, 'creature_groups_id' => 63, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 231, 'creature_groups_id' => 63, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 232, 'creature_groups_id' => 63, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 233, 'creature_groups_id' => 63, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 234, 'creature_groups_id' => 63, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 235, 'creature_groups_id' => 63, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 236, 'creature_groups_id' => 63, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 237, 'creature_groups_id' => 63, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 238, 'creature_groups_id' => 63, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 239, 'creature_groups_id' => 63, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 240, 'creature_groups_id' => 63, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 241, 'creature_groups_id' => 63, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 242, 'creature_groups_id' => 63, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 243, 'creature_groups_id' => 63, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 244, 'creature_groups_id' => 63, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 245, 'creature_groups_id' => 63, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 246, 'creature_groups_id' => 63, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 247, 'creature_groups_id' => 63, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 248, 'creature_groups_id' => 64, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 249, 'creature_groups_id' => 64, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 250, 'creature_groups_id' => 64, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 251, 'creature_groups_id' => 64, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 252, 'creature_groups_id' => 64, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 253, 'creature_groups_id' => 64, 'weight' => 1, 'priority' => null, 'score_req' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			]);

		DB::table('spawn_rules')->insert([
			['creatures_id' => null, 'creature_groups_id' => 1, 'zones_id' => 1, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 2, 'zones_id' => 2, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 3, 'zones_id' => 3, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 4, 'zones_id' => 4, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 5, 'zones_id' => 5, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 6, 'zones_id' => 6, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 7, 'zones_id' => 7, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 9, 'zones_id' => 9, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 10, 'zones_id' => 12, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 11, 'zones_id' => 10, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 12, 'zones_id' => 11, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 13, 'zones_id' => 13, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 14, 'zones_id' => 14, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 5, 'creature_groups_id' => null, 'zones_id' => null, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => 104, 'chance' => 1, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => true, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 17, 'creature_groups_id' => null, 'zones_id' => null, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => 239, 'chance' => 0.75, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => 2000, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 23, 'creature_groups_id' => null, 'zones_id' => null, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => 298, 'chance' => 1, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 24, 'creature_groups_id' => null, 'zones_id' => 8, 'zone_level' => 0, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => 1, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 25, 'creature_groups_id' => null, 'zones_id' => 8, 'zone_level' => 1, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => 1, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 26, 'creature_groups_id' => null, 'zones_id' => 8, 'zone_level' => 2, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => 1, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 27, 'creature_groups_id' => null, 'zones_id' => 8, 'zone_level' => 3, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => 1, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 32, 'creature_groups_id' => null, 'zones_id' => null, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => 337, 'chance' => 0.75, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => 2000, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 32, 'creature_groups_id' => null, 'zones_id' => null, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => 341, 'chance' => 0.75, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => 2000, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 32, 'creature_groups_id' => null, 'zones_id' => null, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => 357, 'chance' => 0.75, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => 2000, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 32, 'creature_groups_id' => null, 'zones_id' => null, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => 361, 'chance' => 0.75, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => 2000, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 36, 'creature_groups_id' => null, 'zones_id' => null, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => 362, 'chance' => 1, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 41, 'creature_groups_id' => null, 'zones_id' => null, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => 379, 'chance' => 0.25, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 41, 'creature_groups_id' => null, 'zones_id' => null, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => 380, 'chance' => 0.25, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 54, 'creature_groups_id' => null, 'zones_id' => null, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => 552, 'chance' => 0.25, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 54, 'creature_groups_id' => null, 'zones_id' => null, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => 562, 'chance' => 0.25, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 82, 'creature_groups_id' => null, 'zones_id' => 18, 'zone_level' => 0, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => 1, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 83, 'creature_groups_id' => null, 'zones_id' => 18, 'zone_level' => 1, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => 1, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 84, 'creature_groups_id' => null, 'zones_id' => 18, 'zone_level' => 2, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => 1, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 85, 'creature_groups_id' => null, 'zones_id' => 18, 'zone_level' => 3, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => 1, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 23, 'zones_id' => 20, 'zone_level' => 0, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 24, 'zones_id' => 20, 'zone_level' => 1, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 25, 'zones_id' => 20, 'zone_level' => 2, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 30, 'zones_id' => 22, 'zone_level' => 0, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 31, 'zones_id' => 22, 'zone_level' => -1, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 32, 'zones_id' => 22, 'zone_level' => -2, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 33, 'zones_id' => 23, 'zone_level' => 0, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 34, 'zones_id' => 23, 'zone_level' => -1, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 35, 'zones_id' => 23, 'zone_level' => -2, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 36, 'zones_id' => 23, 'zone_level' => -3, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 37, 'zones_id' => 23, 'zone_level' => -4, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 38, 'zones_id' => 23, 'zone_level' => -5, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 123, 'creature_groups_id' => null, 'zones_id' => null, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => 1125, 'chance' => 1, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 39, 'zones_id' => 24, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 132, 'creature_groups_id' => null, 'zones_id' => null, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => 1201, 'chance' => 1, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 42, 'zones_id' => 25, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 43, 'zones_id' => 26, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 46, 'zones_id' => 30, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 47, 'zones_id' => 33, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 48, 'zones_id' => 31, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 49, 'zones_id' => 35, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 50, 'zones_id' => 32, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 51, 'zones_id' => 34, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 52, 'zones_id' => 27, 'zone_level' => 0, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 53, 'zones_id' => 27, 'zone_level' => -1, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 54, 'zones_id' => 27, 'zone_level' => -2, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 55, 'zones_id' => 27, 'zone_level' => -3, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 56, 'zones_id' => 27, 'zone_level' => -4, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 57, 'zones_id' => 27, 'zone_level' => -5, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 58, 'zones_id' => 28, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 59, 'zones_id' => 36, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => 204, 'creature_groups_id' => null, 'zones_id' => null, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => 2273, 'chance' => 1, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 60, 'zones_id' => 37, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 61, 'zones_id' => 38, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 62, 'zones_id' => 39, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['creatures_id' => null, 'creature_groups_id' => 63, 'zones_id' => 29, 'zone_level' => null, 'zone_areas_id' => null, 'rooms_id' => null, 'chance' => null, 'spawn_hour' => null, 'random_hour' => false, 'priority' => null, 'score_req' => null, 'spawns_once' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			]);
		}
	}
