<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CreatureData extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
		{
		// Starts @ id 5
		DB::table('creatures')->insert([
			['name' => 'Town Guard', 'attack_text' => 'Town Guard attacks you with his shiney sword.', 'img_src' => 'townguard.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 150000, 'armor' => 39,  'magic_resistance' => 0.0, 'scroll_resistance' => 0, 'damage_low' => 60, 'damage_high' => 60, 'attacks_per_round' => 1, 'award_xp' => 0, 'xp_variation' => 0, 'award_gold' => 0, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Hermit Crab', 'attack_text' => 'The small crab flexes his claws at you, then pinches you!', 'img_src' => 'HermitCrab.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 60, 'armor' => 1,  'magic_resistance' => 0.0, 'scroll_resistance' => 0, 'damage_low' => 1, 'damage_high' => 20, 'attacks_per_round' => 1, 'award_xp' => 550, 'xp_variation' => 0.1, 'award_gold' => 1, 'gold_variation' => 0, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Crab', 'attack_text' => 'The small crab flexes his claws at you, then pinches you!', 'img_src' => 'Crab.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 60, 'armor' => 7,  'magic_resistance' => 0.0, 'scroll_resistance' => 0, 'damage_low' => 1, 'damage_high' => 28, 'attacks_per_round' => 1, 'award_xp' => 660, 'xp_variation' => 0.1, 'award_gold' => 1, 'gold_variation' => 0, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Stone Crab', 'attack_text' => 'The small crab flexes his claws at you, then pinches you!', 'img_src' => 'StoneCrab.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 60, 'armor' => 12,  'magic_resistance' => 0.0, 'scroll_resistance' => 0, 'damage_low' => 1, 'damage_high' => 35, 'attacks_per_round' => 1, 'award_xp' => 900, 'xp_variation' => 0.1, 'award_gold' => 1, 'gold_variation' => 0, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Bat', 'attack_text' => 'Bat dives at you trying to bite your neck.', 'img_src' => 'bat.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => 2, 'alignment_strength' => 0.1, 'health' => 90, 'armor' => 16,  'magic_resistance' => 0.0, 'scroll_resistance' => 0, 'damage_low' => 1, 'damage_high' => 40, 'attacks_per_round' => 1, 'award_xp' => 1000, 'xp_variation' => 0.1, 'award_gold' => 1, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Goblin', 'attack_text' => 'Goblin scrapes at you with its long sharp claws.', 'img_src' => 'goblin.gif', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => 3, 'alignment_strength' => 0.1, 'health' => 130, 'armor' => 26,  'magic_resistance' => 0.0, 'scroll_resistance' => 0, 'damage_low' => 1, 'damage_high' => 55, 'attacks_per_round' => 1, 'award_xp' => 1250, 'xp_variation' => 0.1, 'award_gold' => 2, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Gypsy', 'attack_text' => 'Gypsy claws at your face.', 'img_src' => 'gypsy.gif', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 200, 'armor' => 36,  'magic_resistance' => 0.0, 'scroll_resistance' => 0, 'damage_low' => 1, 'damage_high' => 70, 'attacks_per_round' => 1, 'award_xp' => 1335, 'xp_variation' => 0.1, 'award_gold' => 2, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Convict', 'attack_text' => 'Convict attacks you with a sharpened tooth brush.', 'img_src' => 'convict.gif', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 300, 'armor' => 46,  'magic_resistance' => 0.0, 'scroll_resistance' => 0, 'damage_low' => 1, 'damage_high' => 85, 'attacks_per_round' => 1, 'award_xp' => 1750, 'xp_variation' => 0.1, 'award_gold' => 2, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Sewer Rat', 'attack_text' => 'Rat claws at your flesh tearing at your limbs.', 'img_src' => 'rat.gif', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 325, 'armor' => 50,  'magic_resistance' => 0.0, 'scroll_resistance' => 0, 'damage_low' => 1, 'damage_high' => 50, 'attacks_per_round' => 1, 'award_xp' => 2250, 'xp_variation' => 0.1, 'award_gold' => 3, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Warrior', 'attack_text' => 'Warrior rakes your body.', 'img_src' => 'warrior.gif', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 400, 'armor' => 58,  'magic_resistance' => 0.0, 'scroll_resistance' => 0, 'damage_low' => 1, 'damage_high' => 55, 'attacks_per_round' => 1, 'award_xp' => 3200, 'xp_variation' => 0.1, 'award_gold' => 4, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Drunken Monk', 'attack_text' => 'Monk staggers at you and flails his arms.', 'img_src' => 'monk.gif', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 800, 'armor' => 71,  'magic_resistance' => 0.0, 'scroll_resistance' => 0, 'damage_low' => 1, 'damage_high' => 100, 'attacks_per_round' => 1, 'award_xp' => 6000, 'xp_variation' => 0.1, 'award_gold' => 6, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Old Wizard', 'attack_text' => 'Fire engulfs your entire being.', 'img_src' => 'wizard.jpeg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => 1, 'alignment_strength' => 0.1, 'health' => 1000, 'armor' => 79,  'magic_resistance' => 0.0, 'scroll_resistance' => 0, 'damage_low' => 1, 'damage_high' => 150, 'attacks_per_round' => 1, 'award_xp' => 5135, 'xp_variation' => 0.1, 'award_gold' => 7, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Druid', 'attack_text' => 'Druid attacks you with a war hammer..', 'img_src' => 'druid.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 2500, 'armor' => 142,  'magic_resistance' => 0.0, 'scroll_resistance' => 0, 'damage_low' => 1, 'damage_high' => 300, 'attacks_per_round' => 1, 'award_xp' => 9400, 'xp_variation' => 0.1, 'award_gold' => 20, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Avarial', 'attack_text' => 'An Avarial attacks you with a sword..', 'img_src' => 'avarial.jpeg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => 2, 'alignment_strength' => 0.1, 'health' => 3000, 'armor' => 40,  'magic_resistance' => 0.0, 'scroll_resistance' => 0, 'damage_low' => 1, 'damage_high' => 112, 'attacks_per_round' => 3, 'award_xp' => 11000, 'xp_variation' => 0.1, 'award_gold' => 18, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Kreen', 'attack_text' => 'A kreen attacks you with sharp claws and teeth.', 'img_src' => 'kreen.jpeg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 3500, 'armor' => 22,  'magic_resistance' => 0.0, 'scroll_resistance' => 0, 'damage_low' => 1, 'damage_high' => 60, 'attacks_per_round' => 4, 'award_xp' => 11500, 'xp_variation' => 0.1, 'award_gold' => 18, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Unicorn', 'attack_text' => 'You see a unicorn.', 'img_src' => 'unicorn.jpb', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => 3, 'alignment_strength' => 0.1, 'health' => 150000, 'armor' => 328,  'magic_resistance' => 0.0, 'scroll_resistance' => 0, 'damage_low' => 1, 'damage_high' => 375, 'attacks_per_round' => 4, 'award_xp' => 100000, 'xp_variation' => 0.1, 'award_gold' => 900, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Zombie', 'attack_text' => 'A zombie atacks you.', 'img_src' => 'zombie.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 1450, 'armor' => 100,  'magic_resistance' => 0.0, 'scroll_resistance' => 0, 'damage_low' => 1, 'damage_high' => 250, 'attacks_per_round' => 1, 'award_xp' => 8500, 'xp_variation' => 0.1, 'award_gold' => 8, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Skeleton Warrior', 'attack_text' => 'A Skeleton Warrior attacks you..', 'img_src' => 'mystickel.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 1950, 'armor' => 111,  'magic_resistance' => 0.0, 'scroll_resistance' => 0, 'damage_low' => 1, 'damage_high' => 250, 'attacks_per_round' => 1, 'award_xp' => 8300, 'xp_variation' => 0.1, 'award_gold' => 13, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Blob', 'attack_text' => 'You are swallowed alive.', 'img_src' => 'blob.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 2200, 'armor' => 118,  'magic_resistance' => 0.0, 'scroll_resistance' => 0, 'damage_low' => 1, 'damage_high' => 200, 'attacks_per_round' => 1, 'award_xp' => 9500, 'xp_variation' => 0.1, 'award_gold' => 13, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Nightstalker', 'attack_text' => 'You feel a sharp pain in your skull..', 'img_src' => 'nightst.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 2300, 'armor' => 132,  'magic_resistance' => 0.0, 'scroll_resistance' => 0, 'damage_low' => 1, 'damage_high' => 200, 'attacks_per_round' => 1, 'award_xp' => 10000, 'xp_variation' => 0.1, 'award_gold' => 13, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Old Witch', 'attack_text' => 'An old witch casts a spell on you.', 'img_src' => 'witch.jpb', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => 1, 'alignment_strength' => 0.1, 'health' => 1200, 'armor' => 81,  'magic_resistance' => 0.0, 'scroll_resistance' => 0, 'damage_low' => 1, 'damage_high' => 100, 'attacks_per_round' => 1, 'award_xp' => 7925, 'xp_variation' => 0.1, 'award_gold' => 9, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Dead Knight', 'attack_text' => 'A Skeleton Knight attacks you.', 'img_src' => 'skeletonkn.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 50000, 'armor' => 250,  'magic_resistance' => 0.0, 'scroll_resistance' => 0, 'damage_low' => 1, 'damage_high' => 305, 'attacks_per_round' => 2, 'award_xp' => 36000, 'xp_variation' => 0.1, 'award_gold' => 225, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Rookie Guard', 'attack_text' => 'Rookie Guard stumbles towards you', 'img_src' => 'Rookieguards.jpeg', 'is_hostile' => false, 'is_blocking' => true, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 4000, 'armor' => 126,  'magic_resistance' => 0.0, 'scroll_resistance' => 0, 'damage_low' => 1, 'damage_high' => 200, 'attacks_per_round' => 1, 'award_xp' => 8000, 'xp_variation' => 0.1, 'award_gold' => 30, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Castle Guard', 'attack_text' => 'Guard charges on the attack', 'img_src' => 'Castleguard.jpeg', 'is_hostile' => false, 'is_blocking' => true, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 5300, 'armor' => 79,  'magic_resistance' => 0.0, 'scroll_resistance' => 0, 'damage_low' => 1, 'damage_high' => 200, 'attacks_per_round' => 2, 'award_xp' => 11000, 'xp_variation' => 0.1, 'award_gold' => 40, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Elite Guard', 'attack_text' => 'Elite Guard jumps you before you can defend yourself.', 'img_src' => 'Eliteguard.jpg', 'is_hostile' => false, 'is_blocking' => true, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 6700, 'armor' => 207,  'magic_resistance' => 0.0, 'scroll_resistance' => 0, 'damage_low' => 1, 'damage_high' => 200, 'attacks_per_round' => 1, 'award_xp' => 10000, 'xp_variation' => 0.1, 'award_gold' => 50, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Drakmor Dragon', 'attack_text' => 'Dragons breath engulfs you with flames', 'img_src' => 'Drakmordragon.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => 2, 'alignment_strength' => 0.1, 'health' => 8000, 'armor' => 228,  'magic_resistance' => 0.0, 'scroll_resistance' => 0, 'damage_low' => 1, 'damage_high' => 250, 'attacks_per_round' => 1, 'award_xp' => 19000, 'xp_variation' => 0.1, 'award_gold' => 55, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],

		]);
		}
	}
