<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CreatureData extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
		{
		// Starts @ id 5
		DB::table('creatures')->insert([
			['name' => 'Town Guard', 'attack_text' => 'Town Guard attacks you with his shiney sword.', 'img_src' => 'townguard.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 150000, 'armor' => 39,  'magic_resistance' => 0.0, 'scroll_resistance' => 0.0, 'damage_low' => 60, 'damage_high' => 60, 'attacks_per_round' => 1, 'award_xp' => 0, 'xp_variation' => 0, 'award_gold' => 0, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Hermit Crab', 'attack_text' => 'The small crab flexes his claws at you, then pinches you!', 'img_src' => 'HermitCrab.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 60, 'armor' => 1,  'magic_resistance' => 0.0, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 20, 'attacks_per_round' => 1, 'award_xp' => 550, 'xp_variation' => 0.1, 'award_gold' => 1, 'gold_variation' => 0, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Crab', 'attack_text' => 'The small crab flexes his claws at you, then pinches you!', 'img_src' => 'Crab.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 60, 'armor' => 7,  'magic_resistance' => 0.0, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 28, 'attacks_per_round' => 1, 'award_xp' => 660, 'xp_variation' => 0.1, 'award_gold' => 1, 'gold_variation' => 0, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Stone Crab', 'attack_text' => 'The small crab flexes his claws at you, then pinches you!', 'img_src' => 'StoneCrab.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 60, 'armor' => 12,  'magic_resistance' => 0.0, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 35, 'attacks_per_round' => 1, 'award_xp' => 900, 'xp_variation' => 0.1, 'award_gold' => 1, 'gold_variation' => 0, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Bat', 'attack_text' => 'Bat dives at you trying to bite your neck.', 'img_src' => 'bat.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => 2, 'alignment_strength' => 0.1, 'health' => 90, 'armor' => 16,  'magic_resistance' => 0.0, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 40, 'attacks_per_round' => 1, 'award_xp' => 1000, 'xp_variation' => 0.1, 'award_gold' => 1, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Goblin', 'attack_text' => 'Goblin scrapes at you with its long sharp claws.', 'img_src' => 'goblin.gif', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => 3, 'alignment_strength' => 0.1, 'health' => 130, 'armor' => 26,  'magic_resistance' => 0.0, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 55, 'attacks_per_round' => 1, 'award_xp' => 1250, 'xp_variation' => 0.1, 'award_gold' => 2, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Gypsy', 'attack_text' => 'Gypsy claws at your face.', 'img_src' => 'gypsy.gif', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 130, 'armor' => 36,  'magic_resistance' => 0.0, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 70, 'attacks_per_round' => 1, 'award_xp' => 1335, 'xp_variation' => 0.1, 'award_gold' => 2, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Convict', 'attack_text' => 'Convict attacks you with a sharpened tooth brush.', 'img_src' => 'convict.gif', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 150, 'armor' => 46,  'magic_resistance' => 0.0, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 85, 'attacks_per_round' => 1, 'award_xp' => 1750, 'xp_variation' => 0.1, 'award_gold' => 2, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Sewer Rat', 'attack_text' => 'Rat claws at your flesh tearing at your limbs.', 'img_src' => 'rat.gif', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 325, 'armor' => 50,  'magic_resistance' => 0.0, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 50, 'attacks_per_round' => 1, 'award_xp' => 2250, 'xp_variation' => 0.1, 'award_gold' => 3, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Warrior', 'attack_text' => 'Warrior rakes your body.', 'img_src' => 'warrior.gif', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 400, 'armor' => 58,  'magic_resistance' => 0.0, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 55, 'attacks_per_round' => 1, 'award_xp' => 3200, 'xp_variation' => 0.1, 'award_gold' => 4, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Drunken Monk', 'attack_text' => 'Monk staggers at you and flails his arms.', 'img_src' => 'monk.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 800, 'armor' => 71,  'magic_resistance' => 0.0, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 100, 'attacks_per_round' => 1, 'award_xp' => 6000, 'xp_variation' => 0.1, 'award_gold' => 6, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Old Wizard', 'attack_text' => 'Fire engulfs your entire being.', 'img_src' => 'wizard.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => 1, 'alignment_strength' => 0.1, 'health' => 1000, 'armor' => 79,  'magic_resistance' => 0.02, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 150, 'attacks_per_round' => 1, 'award_xp' => 5135, 'xp_variation' => 0.1, 'award_gold' => 7, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Druid', 'attack_text' => 'Druid attacks you with a war hammer..', 'img_src' => 'druid.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 2500, 'armor' => 142,  'magic_resistance' => 0.0, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 300, 'attacks_per_round' => 1, 'award_xp' => 9400, 'xp_variation' => 0.1, 'award_gold' => 20, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Avarial', 'attack_text' => 'An Avarial attacks you with a sword..', 'img_src' => 'avarial.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => 2, 'alignment_strength' => 0.1, 'health' => 3000, 'armor' => 40,  'magic_resistance' => 0.0, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 112, 'attacks_per_round' => 3, 'award_xp' => 11000, 'xp_variation' => 0.1, 'award_gold' => 18, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Kreen', 'attack_text' => 'A kreen attacks you with sharp claws and teeth.', 'img_src' => 'kreen.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 3500, 'armor' => 22,  'magic_resistance' => 0.1, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 60, 'attacks_per_round' => 4, 'award_xp' => 11500, 'xp_variation' => 0.1, 'award_gold' => 18, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Unicorn', 'attack_text' => 'You see a unicorn.', 'img_src' => 'unicorn.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => 3, 'alignment_strength' => 0.1, 'health' => 150000, 'armor' => 328,  'magic_resistance' => 0.30, 'scroll_resistance' => 0.45, 'damage_low' => 1, 'damage_high' => 375, 'attacks_per_round' => 4, 'award_xp' => 100000, 'xp_variation' => 0.1, 'award_gold' => 900, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Zombie', 'attack_text' => 'A zombie atacks you.', 'img_src' => 'zombie.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 1450, 'armor' => 100,  'magic_resistance' => 0.0, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 250, 'attacks_per_round' => 1, 'award_xp' => 8500, 'xp_variation' => 0.1, 'award_gold' => 8, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Skeleton Warrior', 'attack_text' => 'A Skeleton Warrior attacks you..', 'img_src' => 'mystickel.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 1950, 'armor' => 111,  'magic_resistance' => 0.0, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 250, 'attacks_per_round' => 1, 'award_xp' => 8300, 'xp_variation' => 0.1, 'award_gold' => 13, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Blob', 'attack_text' => 'You are swallowed alive.', 'img_src' => 'blob.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 2200, 'armor' => 118,  'magic_resistance' => 0.05, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 200, 'attacks_per_round' => 1, 'award_xp' => 9500, 'xp_variation' => 0.1, 'award_gold' => 13, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Nightstalker', 'attack_text' => 'You feel a sharp pain in your skull..', 'img_src' => 'nightst.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 2300, 'armor' => 132,  'magic_resistance' => 0.05, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 200, 'attacks_per_round' => 1, 'award_xp' => 10000, 'xp_variation' => 0.1, 'award_gold' => 13, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Old Witch', 'attack_text' => 'An old witch casts a spell on you.', 'img_src' => 'witch.jpb', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => 1, 'alignment_strength' => 0.1, 'health' => 1200, 'armor' => 81,  'magic_resistance' => 0.0, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 100, 'attacks_per_round' => 1, 'award_xp' => 7925, 'xp_variation' => 0.1, 'award_gold' => 9, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Dead Knight', 'attack_text' => 'A Skeleton Knight attacks you.', 'img_src' => 'skeletonkn.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 50000, 'armor' => 250,  'magic_resistance' => 0.1, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 305, 'attacks_per_round' => 2, 'award_xp' => 36000, 'xp_variation' => 0.1, 'award_gold' => 225, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Rookie Guard', 'attack_text' => 'Rookie Guard stumbles towards you', 'img_src' => 'Rookieguards.jpg', 'is_hostile' => false, 'is_blocking' => true, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 4000, 'armor' => 126,  'magic_resistance' => 0.0, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 200, 'attacks_per_round' => 1, 'award_xp' => 8000, 'xp_variation' => 0.1, 'award_gold' => 30, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Castle Guard', 'attack_text' => 'Guard charges on the attack', 'img_src' => 'Castleguard.jpg', 'is_hostile' => false, 'is_blocking' => true, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 5300, 'armor' => 79,  'magic_resistance' => 0.0, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 200, 'attacks_per_round' => 2, 'award_xp' => 11000, 'xp_variation' => 0.1, 'award_gold' => 40, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Elite Guard', 'attack_text' => 'Elite Guard jumps you before you can defend yourself.', 'img_src' => 'Eliteguard.jpg', 'is_hostile' => false, 'is_blocking' => true, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 6700, 'armor' => 207,  'magic_resistance' => 0.0, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 200, 'attacks_per_round' => 1, 'award_xp' => 10000, 'xp_variation' => 0.1, 'award_gold' => 50, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Drakmor Dragon', 'attack_text' => 'Dragons breath engulfs you with flames', 'img_src' => 'Drakmordragon.jpg', 'is_hostile' => false, 'is_blocking' => true, 'alignments_id' => 2, 'alignment_strength' => 0.1, 'health' => 8000, 'armor' => 228,  'magic_resistance' => 0.05, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 250, 'attacks_per_round' => 1, 'award_xp' => 19000, 'xp_variation' => 0.1, 'award_gold' => 55, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Dogfish Child', 'attack_text' => 'Tiny teeth scrape at your armor', 'img_src' => 'waterworld.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => 4, 'alignment_strength' => 0.1, 'health' => 8000, 'armor' => 230,  'magic_resistance' => 0.0, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 300, 'attacks_per_round' => 1, 'award_xp' => 20000, 'xp_variation' => 0.1, 'award_gold' => 60, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Dogfish', 'attack_text' => 'Dogfish bites at your legs', 'img_src' => 'waterworld2.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => 4, 'alignment_strength' => 0.1, 'health' => 8500, 'armor' => 230,  'magic_resistance' => 0.0, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 300, 'attacks_per_round' => 1, 'award_xp' => 20000, 'xp_variation' => 0.1, 'award_gold' => 60, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Dogfish Princess', 'attack_text' => 'Princess shreaks at you bursting your ear drums', 'img_src' => 'Dogfishprincess.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => 4, 'alignment_strength' => 0.1, 'health' => 9000, 'armor' => 230,  'magic_resistance' => 0.0, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 300, 'attacks_per_round' => 1, 'award_xp' => 18000, 'xp_variation' => 0.1, 'award_gold' => 60, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Dogfish Queen', 'attack_text' => 'Dogfish royalty gives you the look', 'img_src' => 'Dogfishqueen.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => 4, 'alignment_strength' => 0.1, 'health' => 10000, 'armor' => 230,  'magic_resistance' => 0.0, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 300, 'attacks_per_round' => 1, 'award_xp' => 18000, 'xp_variation' => 0.1, 'award_gold' => 70, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Kraken', 'attack_text' => "The Kraken flails at you with it's tentacles", 'img_src' => 'kraken.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => 4, 'alignment_strength' => 0.1, 'health' => 150000, 'armor' => 305,  'magic_resistance' => 0.3, 'scroll_resistance' => 0.45, 'damage_low' => 1, 'damage_high' => 350, 'attacks_per_round' => 4, 'award_xp' => 100000, 'xp_variation' => 0.1, 'award_gold' => 800, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Vampire Bat', 'attack_text' => 'You feel a sharp stinging and ripping at your neck', 'img_src' => 'bat.gif', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => 2, 'alignment_strength' => 0.1, 'health' => 15000, 'armor' => 329,  'magic_resistance' => 0.05, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 400, 'attacks_per_round' => 1, 'award_xp' => 30000, 'xp_variation' => 0.1, 'award_gold' => 110, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Troll', 'attack_text' => 'Charges at you with nasty teeth and nails', 'img_src' => 'troll.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => 3, 'alignment_strength' => 0.1, 'health' => 17000, 'armor' => 379,  'magic_resistance' => 0.15, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 475, 'attacks_per_round' => 1, 'award_xp' => 30000, 'xp_variation' => 0.1, 'award_gold' => 150, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Elf', 'attack_text' => 'Your armour is pierced by a silver sword', 'img_src' => 'elf.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 19000, 'armor' => 427,  'magic_resistance' => 0.2, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 550, 'attacks_per_round' => 1, 'award_xp' => 30000, 'xp_variation' => 0.1, 'award_gold' => 150, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Park Ranger', 'attack_text' => 'Ranger throws his shiny badge at you', 'img_src' => 'ranger.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => 3, 'alignment_strength' => 0.1, 'health' => 15000, 'armor' => 176,  'magic_resistance' => 0.15, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 150, 'attacks_per_round' => 1, 'award_xp' => 20000, 'xp_variation' => 0.1, 'award_gold' => 70, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Goat', 'attack_text' => 'Horns pierce through your armor', 'img_src' => 'goat.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 14000, 'armor' => 274,  'magic_resistance' => 0.0, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 350, 'attacks_per_round' => 1, 'award_xp' => 25000, 'xp_variation' => 0.1, 'award_gold' => 90, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Bear', 'attack_text' => 'Bear claws at you', 'img_src' => 'bear.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 14000, 'armor' => 277,  'magic_resistance' => 0.0, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 350, 'attacks_per_round' => 1, 'award_xp' => 25000, 'xp_variation' => 0.1, 'award_gold' => 90, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Masked Ranger', 'attack_text' => 'A blur of metal slices at your soul', 'img_src' => 'maskranger.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => 2, 'alignment_strength' => 0.1, 'health' => 17000, 'armor' => 282,  'magic_resistance' => 0.0, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 350, 'attacks_per_round' => 1, 'award_xp' => 25000, 'xp_variation' => 0.1, 'award_gold' => 95, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Pegasus Scout', 'attack_text' => 'A flash of wing slices at your soul', 'img_src' => 'winged.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => 2, 'alignment_strength' => 0.1, 'health' => 30000, 'armor' => 325,  'magic_resistance' => 0.0, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 300, 'attacks_per_round' => 1, 'award_xp' => 25000, 'xp_variation' => 0.1, 'award_gold' => 225, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Hydra', 'attack_text' => 'Hydra bashes you with one of its heads', 'img_src' => 'Hydra.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => 3, 'alignment_strength' => 0.2, 'health' => 50000, 'armor' => 127,  'magic_resistance' => 0.1, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 185, 'attacks_per_round' => 3, 'award_xp' => 25000, 'xp_variation' => 0.1, 'award_gold' => 370, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Dumb Strong Ogre', 'attack_text' => 'Ogre bashes you with a big wood club', 'img_src' => 'ogre.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 26000, 'armor' => 328,  'magic_resistance' => 0.0, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 400, 'attacks_per_round' => 1, 'award_xp' => 27000, 'xp_variation' => 0.1, 'award_gold' => 180, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Dumber Stronger Ogre', 'attack_text' => 'Ogre bashes you with a big wood club', 'img_src' => 'dumber.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 28000, 'armor' => 353,  'magic_resistance' => 0.0, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 450, 'attacks_per_round' => 1, 'award_xp' => 23500, 'xp_variation' => 0.1, 'award_gold' => 200, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Dumbest Strongest Ogre', 'attack_text' => 'Ogre bashes you with a big wood club', 'img_src' => 'dumbest.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 32000, 'armor' => 377,  'magic_resistance' => 0.0, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 500, 'attacks_per_round' => 1, 'award_xp' => 24000, 'xp_variation' => 0.1, 'award_gold' => 220, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Deer', 'attack_text' => 'Deer beats you with its hoofs', 'img_src' => 'deer.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => 3, 'alignment_strength' => 0.1, 'health' => 57000, 'armor' => 446,  'magic_resistance' => 0.0, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 80, 'attacks_per_round' => 4, 'award_xp' => 50000, 'xp_variation' => 0.1, 'award_gold' => 360, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Griffen', 'attack_text' => 'A Griffens claws tear at you', 'img_src' => 'griffen.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => 2, 'alignment_strength' => 0.1, 'health' => 50000, 'armor' => 280,  'magic_resistance' => 0.2, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 250, 'attacks_per_round' => 1, 'award_xp' => 50000, 'xp_variation' => 0.1, 'award_gold' => 220, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Harpy', 'attack_text' => 'loud shreiks tear at your mind', 'img_src' => 'harpy2.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => 2, 'alignment_strength' => 0.1, 'health' => 57000, 'armor' => 477,  'magic_resistance' => 0.2, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 450, 'attacks_per_round' => 1, 'award_xp' => 38000, 'xp_variation' => 0.1, 'award_gold' => 360, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Archer', 'attack_text' => 'Arrows pierce your armor', 'img_src' => 'archer.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 60000, 'armor' => 378,  'magic_resistance' => 0.0, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 300, 'attacks_per_round' => 2, 'award_xp' => 52000, 'xp_variation' => 0.1, 'award_gold' => 360, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Imp', 'attack_text' => "The Creature attacks you with it's spells", 'img_src' => 'imp.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => 1, 'alignment_strength' => 0.1, 'health' => 60000, 'armor' => 578,  'magic_resistance' => 0.25, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 550, 'attacks_per_round' => 1, 'award_xp' => 40000, 'xp_variation' => 0.1, 'award_gold' => 465, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Wyvern', 'attack_text' => "Wyvern attacks you with it's fire breath", 'img_src' => 'wyvern.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => 1, 'alignment_strength' => 0.1, 'health' => 65000, 'armor' => 581,  'magic_resistance' => 0.25, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 550, 'attacks_per_round' => 1, 'award_xp' => 45000, 'xp_variation' => 0.1, 'award_gold' => 465, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Serpentfly', 'attack_text' => 'Swarms of serpentflies bite and sting you', 'img_src' => 'serpentfly.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => 2, 'alignment_strength' => 0.1, 'health' => 60000, 'armor' => 575,  'magic_resistance' => 0.25, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 550, 'attacks_per_round' => 1, 'award_xp' => 45000, 'xp_variation' => 0.1, 'award_gold' => 465, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Basilisk', 'attack_text' => 'Basilisk charges at you with acid and teeth', 'img_src' => 'basilisk.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => 3, 'alignment_strength' => 0.1, 'health' => 65000, 'armor' => 577,  'magic_resistance' => 0.3, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 550, 'attacks_per_round' => 1, 'award_xp' => 45000, 'xp_variation' => 0.1, 'award_gold' => 465, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Gorgon', 'attack_text' => 'The Gorgon looks at you', 'img_src' => 'gorgon.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => 3, 'alignment_strength' => 0.1, 'health' => 55000, 'armor' => 130,  'magic_resistance' => 0.2, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 250, 'attacks_per_round' => 4, 'award_xp' => 45000, 'xp_variation' => 0.1, 'award_gold' => 465, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Quetzalcoati', 'attack_text' => 'You see a quetzalcoati', 'img_src' => 'quetzalcoati.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => 2, 'alignment_strength' => 0.2, 'health' => 175000, 'armor' => 1229,  'magic_resistance' => 0.3, 'scroll_resistance' => 0.45, 'damage_low' => 1, 'damage_high' => 1675, 'attacks_per_round' => 1, 'award_xp' => 60000, 'xp_variation' => 0.1, 'award_gold' => 900, 'gold_variation' => .5, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],

			['name' => 'Gold Golem', 'attack_text' => 'The Gold Golem smashes you', 'img_src' => 'GoldGolem.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 85000, 'armor' => 678,  'magic_resistance' => 0.1, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 620, 'attacks_per_round' => 1, 'award_xp' => 49500, 'xp_variation' => 0.1, 'award_gold' => 700, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Genie', 'attack_text' => 'Genie blast you with his power', 'img_src' => 'Genie.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 85000, 'armor' => 652,  'magic_resistance' => 0.1, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 600, 'attacks_per_round' => 1, 'award_xp' => 53000, 'xp_variation' => 0.1, 'award_gold' => 675, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Maze Overlord', 'attack_text' => 'The Maze Overlord pulls out his sword and strikes you', 'img_src' => 'darkoverlord11.gif', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 85000, 'armor' => 153,  'magic_resistance' => 0.1, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 150, 'attacks_per_round' => 4, 'award_xp' => 55000, 'xp_variation' => 0.1, 'award_gold' => 700, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Shadow Beast', 'attack_text' => 'The ShadowBeast cuts you with his invisible Sword', 'img_src' => 'essensebeast.gif.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 75000, 'armor' => 198,  'magic_resistance' => 0.1, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 210, 'attacks_per_round' => 3, 'award_xp' => 48000, 'xp_variation' => 0.1, 'award_gold' => 600, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Titan', 'attack_text' => 'Titan swings his mighty axe', 'img_src' => 'titan.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 80000, 'armor' => 630,  'magic_resistance' => 0.1, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 575, 'attacks_per_round' => 1, 'award_xp' => 45000, 'xp_variation' => 0.1, 'award_gold' => 625, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Mage', 'attack_text' => 'The skies turn black as night', 'img_src' => 'mage1.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 85000, 'armor' => 204,  'magic_resistance' => 0.2, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 175, 'attacks_per_round' => 3, 'award_xp' => 47250, 'xp_variation' => 0.1, 'award_gold' => 700, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Shadow', 'attack_text' => 'A Shadow attacks you', 'img_src' => 'shadow.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 75000, 'armor' => 633,  'magic_resistance' => 0.1, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 575, 'attacks_per_round' => 1, 'award_xp' => 50000, 'xp_variation' => 0.1, 'award_gold' => 600, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => "Queen's Guard", 'attack_text' => 'The Queens Guard pierces your armor with her sword', 'img_src' => 'femwarr10.gif', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 70000, 'armor' => 198,  'magic_resistance' => 0.1, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 160, 'attacks_per_round' => 3, 'award_xp' => 42500, 'xp_variation' => 0.1, 'award_gold' => 550, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Black Maze Reaper', 'attack_text' => 'The Reapers Sling slieces at your soul', 'img_src' => 'blackreap1.gif', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 80000, 'armor' => 630,  'magic_resistance' => 0.1, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 575, 'attacks_per_round' => 1, 'award_xp' => 50000, 'xp_variation' => 0.1, 'award_gold' =>650, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Maze Wraith', 'attack_text' => 'The Maze Wraith squeezes the breathe out of you', 'img_src' => 'wraith1.gif', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 75000, 'armor' => 195,  'magic_resistance' => 0.1, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 195, 'attacks_per_round' => 3, 'award_xp' => 50000, 'xp_variation' => 0.1, 'award_gold' => 625, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => "Queen's Warrior", 'attack_text' => 'The Queens Warrior cuts your armor with h er sharp sword', 'img_src' => 'femwarr9.gif', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 75000, 'armor' => 198,  'magic_resistance' => 0.1, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 205, 'attacks_per_round' => 3, 'award_xp' => 46000, 'xp_variation' => 0.1, 'award_gold' => 625, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Bluebat', 'attack_text' => 'the Blue Bats sharp teeth tear at your flesh', 'img_src' => 'bluebat1.gif', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 80000, 'armor' => 654,  'magic_resistance' => 0.1, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 450, 'attacks_per_round' => 1, 'award_xp' => 53000, 'xp_variation' => 0.1, 'award_gold' => 650, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Gremlin', 'attack_text' => 'Gremlin hits you with a ball and chain', 'img_src' => 'gremlin.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 80000, 'armor' => 316,  'magic_resistance' => 0.1, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 310, 'attacks_per_round' => 2, 'award_xp' => 53000, 'xp_variation' => 0.1, 'award_gold' => 650, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Flying Demon', 'attack_text' => 'The Flying Demon attacks you with sharp talons', 'img_src' => 'blueflyingdemon11.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 75000, 'armor' => 628,  'magic_resistance' => 0.1, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 575, 'attacks_per_round' => 1, 'award_xp' => 49000, 'xp_variation' => 0.1, 'award_gold' => 600, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],1
			['name' => 'Centaur', 'attack_text' => 'You have come across a Centaur', 'img_src' => 'centaur.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 70000, 'armor' => 628,  'magic_resistance' => 0.1, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 525, 'attacks_per_round' => 1, 'award_xp' => 49000, 'xp_variation' => 0.1, 'award_gold' => 575, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Grey Maze Reaper', 'attack_text' => 'The Grey Maze Keeper laughs as he throws you to the ground', 'img_src' => 'greyreaperscythe1.gif', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 70000, 'armor' => 139,  'magic_resistance' => 0.1, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 125, 'attacks_per_round' => 4, 'award_xp' => 48000, 'xp_variation' => 0.1, 'award_gold' => 550, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Fairy Warrior', 'attack_text' => 'The Fairy Warrior summons a spell and magic pierces your armor', 'img_src' => 'warriorfairy1.gif', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 80000, 'armor' => 320,  'magic_resistance' => 0.2, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 300, 'attacks_per_round' => 2, 'award_xp' => 53000, 'xp_variation' => 0.1, 'award_gold' => 650, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Red Maze Reaper', 'attack_text' => 'The Red Maze Reaper grabs you with his Bloody hand', 'img_src' => 'red3dreaper11.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 80000, 'armor' => 199,  'magic_resistance' => 0.1, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 180, 'attacks_per_round' => 3, 'award_xp' => 51000, 'xp_variation' => 0.1, 'award_gold' => 625, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Green Nymph', 'attack_text' => 'The Green Nymph slices you with her sharp fingernails', 'img_src' => 'greennympf.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 150000, 'armor' => 354,  'magic_resistance' => 0.1, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 315, 'attacks_per_round' => 4, 'award_xp' => 110000, 'xp_variation' => 0.1, 'award_gold' => 1300, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],

			['name' => 'Dungeon Guard', 'attack_text' => 'Dungeon Guard charges on the attack', 'img_src' => 'dungeonguard.gif', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 110000, 'armor' => 780,  'magic_resistance' => 0.1, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 900, 'attacks_per_round' => 1, 'award_xp' => 63000, 'xp_variation' => 0.1, 'award_gold' => 800, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Dungeon Monster', 'attack_text' => 'A Dungeon Monster attacks you', 'img_src' => 'dungeonmonster.gif', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 150000, 'armor' => 880,  'magic_resistance' => 0.1, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 1000, 'attacks_per_round' => 1, 'award_xp' => 120000, 'xp_variation' => 0.1, 'award_gold' => 800, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Dungeon Master', 'attack_text' => 'The Dungeon Master swings his mighty sword', 'img_src' => 'humanguard.gif', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 100000, 'armor' => 806,  'magic_resistance' => 0.1, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 925, 'attacks_per_round' => 1, 'award_xp' => 79750, 'xp_variation' => 0.1, 'award_gold' => 800, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Tortured Criminal', 'attack_text' => 'The Tortured Criminal smacks you with his bloody arm', 'img_src' => 'torturedcriminal.gif', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 90000, 'armor' => 707,  'magic_resistance' => 0.1, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 825, 'attacks_per_round' => 1, 'award_xp' => 49000, 'xp_variation' => 0.1, 'award_gold' => 725, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Executioner', 'attack_text' => 'The Hand of Death pierces your armor', 'img_src' => 'executioner.gif', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 120000, 'armor' => 405,  'magic_resistance' => 0.1, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 500, 'attacks_per_round' => 2, 'award_xp' => 81000, 'xp_variation' => 0.1, 'award_gold' => 800, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Cutthroat', 'attack_text' => 'A Cutthroat pulls a broken bottle out and atacks you', 'img_src' => 'cutthroat.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 95000, 'armor' => 731,  'magic_resistance' => 0.1, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 850, 'attacks_per_round' => 1, 'award_xp' => 65000, 'xp_variation' => 0.1, 'award_gold' => 760, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Reaper', 'attack_text' => 'The Reaper slices you with its scythe, consuming your soul in darkness', 'img_src' => 'reaper.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 200000, 'armor' => 1187,  'magic_resistance' => 0.1, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 1100, 'attacks_per_round' => 1, 'award_xp' => 120000, 'xp_variation' => 0.1, 'award_gold' => 1200, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Death Reaper', 'attack_text' => 'The Death Reaper slices you with its scythe, consuming your soul in darkness', 'img_src' => 'reaper.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 200000, 'armor' => 1187,  'magic_resistance' => 0.1, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 1100, 'attacks_per_round' => 1, 'award_xp' => 120000, 'xp_variation' => 0.1, 'award_gold' => 1200, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],

			['name' => 'Keep Druid', 'attack_text' => 'Druid attacks you with a war hammer', 'img_src' => 'keepdruid.gif', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 210000, 'armor' => 980,  'magic_resistance' => 0.1, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 1100, 'attacks_per_round' => 1, 'award_xp' => 135000, 'xp_variation' => 0.1, 'award_gold' => 1600, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Minotaur', 'attack_text' => 'Attacks you with a mighty mace', 'img_src' => 'minotaur.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 250000, 'armor' => 1078,  'magic_resistance' => 0.1, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 1200, 'attacks_per_round' => 1, 'award_xp' => 160000, 'xp_variation' => 0.1, 'award_gold' => 1800, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'White Dragon', 'attack_text' => 'Attacks you with his breath and his mighty tail', 'img_src' => 'whitedragon.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 300000, 'armor' => 378,  'magic_resistance' => 0.1, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 500, 'attacks_per_round' => 3, 'award_xp' => 175000, 'xp_variation' => 0.1, 'award_gold' => 1800, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Black Dragon', 'attack_text' => 'Attacks you with his breath and his mighty tail', 'img_src' => 'blackdragon.jpg', 'is_hostile' => false, 'is_blocking' => false, 'alignments_id' => null, 'alignment_strength' => null, 'health' => 400000, 'armor' => 478,  'magic_resistance' => 0.1, 'scroll_resistance' => 0.0, 'damage_low' => 1, 'damage_high' => 600, 'attacks_per_round' => 3, 'award_xp' => 235000, 'xp_variation' => 0.1, 'award_gold' => 2600, 'gold_variation' => .375, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],



			]);
		}
	}
