<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CreateTown extends Seeder
	{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
		{
		DB::table('zones')->insert([
			['name' => 'Town', 'description' => '', 'travel_text' => 'You are standing on a street in Town.', 'bg_color' => null, 'img_src' => null, 'font_color' => null, 'label_color' => null, 'custom_view' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
		]);

		DB::table('zone_levels')->insert([
			['zones_id' => 1, 'level' => 0, 'name' => null, 'inherit_creatures' => true, 'inherit_properties' => true, 'description' => '', 'img_src' => null, 'bg_color' => null, 'font_color' => null, 'label_color' => null, 'custom_view' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
		]);

		// DB::statement("SET session_replication_role = 'replica';");
		DB::table('rooms')->insert([
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => 'The Fountain', 'description' => 'Special unique description', 'img_src' => 'fountain.gif', 'spawns_enabled' => false, 'north_rooms_id' => 21, 'east_rooms_id' => 2, 'south_rooms_id' => 22, 'west_rooms_id' => 25, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 9, 'east_rooms_id' => 15, 'south_rooms_id' => 3, 'west_rooms_id' => 1, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 2, 'east_rooms_id' => null, 'south_rooms_id' => 4, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 3, 'east_rooms_id' => 34, 'south_rooms_id' => null, 'west_rooms_id' => 5, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 4, 'south_rooms_id' => 6, 'west_rooms_id' => 49, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 5, 'east_rooms_id' => 44, 'south_rooms_id' => 7, 'west_rooms_id' => 20, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 6, 'east_rooms_id' => 8, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => 7, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 10, 'east_rooms_id' => 23, 'south_rooms_id' => 2, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			// END 10
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 75, 'south_rooms_id' => 9, 'west_rooms_id' => 11, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 12, 'east_rooms_id' => 10, 'south_rooms_id' => null, 'west_rooms_id' => 61, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 13, 'east_rooms_id' => null, 'south_rooms_id' => 11, 'west_rooms_id' => 24, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => 12, 'west_rooms_id' => 14, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 13, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			// 16:
			// FK ME
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 16, 'south_rooms_id' => 86, 'west_rooms_id' => 2, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 17, 'south_rooms_id' => null, 'west_rooms_id' => 15, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 43, 'east_rooms_id' => 40, 'south_rooms_id' => 18, 'west_rooms_id' => 16, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 17, 'east_rooms_id' => null, 'south_rooms_id' => 36, 'west_rooms_id' => 19, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => 'training_room', 'title' => null, 'description' => 'You are standing in the training room.', 'img_src' => null, 'spawns_enabled' => false, 'north_rooms_id' => null, 'east_rooms_id' => 18, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			// Wall score 27:
			['zones_id' => 1, 'zone_level' => 0, 'uid' => 'flame_wall', 'title' => null, 'description' => 'Before you is the Wall of Flame.', 'img_src' => null, 'spawns_enabled' => false, 'north_rooms_id' => null, 'east_rooms_id' => 6, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => 'inventory', 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => false, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => 1, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => 'quest_log', 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => false, 'north_rooms_id' => 1, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => 'mayor', 'title' => 'Mayor', 'description' => null, 'img_src' => null, 'spawns_enabled' => false, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => 9, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			// END 30
			['zones_id' => 1, 'zone_level' => 0, 'uid' => 'shillatown_foods', 'title' => 'The Food Shop', 'description' => null, 'img_src' => null, 'spawns_enabled' => false, 'north_rooms_id' => null, 'east_rooms_id' => 12, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			// Build more town:
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 72, 'east_rooms_id' => 1, 'south_rooms_id' => 59, 'west_rooms_id' => 26, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 32, 'east_rooms_id' => 25, 'south_rooms_id' => null, 'west_rooms_id' => 27, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 26, 'south_rooms_id' => 33, 'west_rooms_id' => 28, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 73, 'east_rooms_id' => 27, 'south_rooms_id' => null, 'west_rooms_id' => 29, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 28, 'south_rooms_id' => null, 'west_rooms_id' => 30, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 29, 'south_rooms_id' => 31, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 30, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => 'stack_shop', 'title' => '?? Stack Shop ??', 'description' => null, 'img_src' => null, 'spawns_enabled' => false, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => 26, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => 'guild_mana_users', 'title' => '?? Mana Users Guild ??', 'description' => null, 'img_src' => null, 'spawns_enabled' => false, 'north_rooms_id' => 27, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			// END 40
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 35, 'south_rooms_id' => null, 'west_rooms_id' => 4, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 36, 'south_rooms_id' => 45, 'west_rooms_id' => 34, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 18, 'east_rooms_id' => 37, 'south_rooms_id' => null, 'west_rooms_id' => 35, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 39, 'east_rooms_id' => null, 'south_rooms_id' => 38, 'west_rooms_id' => 36, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => 'rentals', 'title' => '?? Rentals ??', 'description' => null, 'img_src' => null, 'spawns_enabled' => false, 'north_rooms_id' => 37, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => 'villager_informant', 'title' => '?? Villager Informant ??', 'description' => null, 'img_src' => null, 'spawns_enabled' => false, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => 37, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 41, 'south_rooms_id' => null, 'west_rooms_id' => 17, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => false, 'north_rooms_id' => 42, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => 40, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => 'defunct_jail', 'title' => '?? Jail ??', 'description' => null, 'img_src' => null, 'spawns_enabled' => false, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => 41, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => 'kill_log', 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => false, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => 17, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			// End 50
			['zones_id' => 1, 'zone_level' => 0, 'uid' => 'shillatown_bank', 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => false, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => 6, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 35, 'east_rooms_id' => 48, 'south_rooms_id' => 47, 'west_rooms_id' => 46, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => 'fire_temple', 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => false, 'north_rooms_id' => null, 'east_rooms_id' => 45, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => 'shillatown_gems', 'title' => '?? Gems ??', 'description' => null, 'img_src' => null, 'spawns_enabled' => false, 'north_rooms_id' => 45, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => 'guild_thieves', 'title' => '?? Thieves Guild ??', 'description' => null, 'img_src' => null, 'spawns_enabled' => false, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => 45, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			// End 55
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 59, 'east_rooms_id' => 5, 'south_rooms_id' => null, 'west_rooms_id' => 50, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 49, 'south_rooms_id' => null, 'west_rooms_id' => 51, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 50, 'south_rooms_id' => 57, 'west_rooms_id' => 52, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 56, 'east_rooms_id' => 51, 'south_rooms_id' => null, 'west_rooms_id' => 53, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 54, 'east_rooms_id' => 52, 'south_rooms_id' => 55, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			// End 60
			['zones_id' => 1, 'zone_level' => 0, 'uid' => 'validator', 'title' => '?? Validator ??', 'description' => null, 'img_src' => null, 'spawns_enabled' => false, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => 53, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => 'trader_bob', 'title' => 'Trader Bob', 'description' => null, 'img_src' => null, 'spawns_enabled' => false, 'north_rooms_id' => 53, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => 'air_temple', 'title' => 'Inside the Air Temple', 'description' => null, 'img_src' => null, 'spawns_enabled' => false, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => 52, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 51, 'east_rooms_id' => null, 'south_rooms_id' => 58, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => 'shillatown_amulets', 'title' => 'Amulet Exchange', 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 57, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			// End 65
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 25, 'east_rooms_id' => null, 'south_rooms_id' => 49, 'west_rooms_id' => 60, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => 'shillatown_graveyard', 'title' => 'Standing in the Graveyard', 'description' => null, 'img_src' => null, 'spawns_enabled' => false, 'north_rooms_id' => null, 'east_rooms_id' => 59, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 11, 'south_rooms_id' => 72, 'west_rooms_id' => 62, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 61, 'south_rooms_id' => null, 'west_rooms_id' => 63, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 68, 'east_rooms_id' => 62, 'south_rooms_id' => null, 'west_rooms_id' => 64, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			// End 70
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 63, 'south_rooms_id' => 73, 'west_rooms_id' => 65, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 66, 'east_rooms_id' => 64, 'south_rooms_id' => 67, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => 'wall_spells', 'title' => '?? Spells Wall ??', 'description' => null, 'img_src' => null, 'spawns_enabled' => false, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => 65, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => 'defunct_courier', 'title' => '?? Courier Corp ??', 'description' => null, 'img_src' => null, 'spawns_enabled' => false, 'north_rooms_id' => 65, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 70, 'east_rooms_id' => 71, 'south_rooms_id' => 63, 'west_rooms_id' => 69, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			// End 75
			['zones_id' => 1, 'zone_level' => 0, 'uid' => 'shillatown_scrolls', 'title' => 'Scrolls?', 'description' => null, 'img_src' => null, 'spawns_enabled' => false, 'north_rooms_id' => null, 'east_rooms_id' => 68, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => 'shillatown_spells', 'title' => 'Spell Trainer', 'description' => null, 'img_src' => null, 'spawns_enabled' => false, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => 68, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => 'water_temple', 'title' => 'Standing inside the Water Temple', 'description' => null, 'img_src' => null, 'spawns_enabled' => false, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => 68, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 61, 'east_rooms_id' => null, 'south_rooms_id' => 25, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 62, 'east_rooms_id' => 74, 'south_rooms_id' => 28, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			// End 80
			['zones_id' => 1, 'zone_level' => 0, 'uid' => 'shillatown_hotel', 'title' => '?? Hotel ??', 'description' => null, 'img_src' => null, 'spawns_enabled' => false, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => 73, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 76, 'south_rooms_id' => null, 'west_rooms_id' => 10, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 82, 'east_rooms_id' => 77, 'south_rooms_id' => 81, 'west_rooms_id' => 75, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 78, 'south_rooms_id' => null, 'west_rooms_id' => 76, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 79, 'east_rooms_id' => null, 'south_rooms_id' => 80, 'west_rooms_id' => 77, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			// End 85
			['zones_id' => 1, 'zone_level' => 0, 'uid' => 'trader_jack', 'title' => "Trader Jack's Exchange", 'description' => null, 'img_src' => null, 'spawns_enabled' => false, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => 78, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => 'guild_fighters', 'title' => '?? Fighters Guild ??', 'description' => null, 'img_src' => null, 'spawns_enabled' => false, 'north_rooms_id' => 78, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => 'earth_temple', 'title' => 'Standing inside the Earth Temple', 'description' => null, 'img_src' => null, 'spawns_enabled' => false, 'north_rooms_id' => 76, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 84, 'east_rooms_id' => 85, 'south_rooms_id' => 76, 'west_rooms_id' => 83, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => 'shillatown_forge', 'title' => 'Standing at the Great Forge', 'description' => null, 'img_src' => null, 'spawns_enabled' => false, 'north_rooms_id' => null, 'east_rooms_id' => 82, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			// End 90
			['zones_id' => 1, 'zone_level' => 0, 'uid' => 'shillatown_weapons', 'title' => 'The Weapons Shop', 'description' => null, 'img_src' => null, 'spawns_enabled' => false, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => 82, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 1, 'zone_level' => 0, 'uid' => 'shillatown_armors', 'title' => 'The Armor Shop', 'description' => null, 'img_src' => null, 'spawns_enabled' => false, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => 82, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			[ 'zones_id' => 1, 'zone_level' => 0, 'uid' => null, 'title' => 'Online listings', 'description' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 15, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
		]);
		// DB::statement("SET session_replication_role = 'origin';");

		// Apply room properties?
		DB::table('rooms')->updateOrInsert(['id' => 1], ['room_properties_id' => 1]);
		DB::table('rooms')->updateOrInsert(['id' => 19], ['room_properties_id' => 2]);
		DB::table('rooms')->updateOrInsert(['id' => 20], ['room_properties_id' => 3]);
		DB::table('rooms')->updateOrInsert(['id' => 44], ['room_properties_id' => 4]);
		DB::table('rooms')->updateOrInsert(['id' => 83], ['room_properties_id' => 5]);
		DB::table('rooms')->updateOrInsert(['id' => 56], ['room_properties_id' => 6]);
		DB::table('rooms')->updateOrInsert(['id' => 81], ['room_properties_id' => 7]);
		DB::table('rooms')->updateOrInsert(['id' => 46], ['room_properties_id' => 8]);
		DB::table('rooms')->updateOrInsert(['id' => 71], ['room_properties_id' => 9]);
		DB::table('rooms')->updateOrInsert(['id' => 70], ['room_properties_id' => 10]);
		DB::table('rooms')->updateOrInsert(['id' => 22], ['room_properties_id' => 11]);
		DB::table('rooms')->updateOrInsert(['id' => 60], ['room_properties_id' => 12]);
		DB::table('rooms')->updateOrInsert(['id' => 43], ['room_properties_id' => 13]);
		DB::table('rooms')->updateOrInsert(['id' => 21], ['room_properties_id' => 14]);

		DB::table('shops')->insert([
			['rooms_id' => 84, 'name' => 'Weapon Shop', 'description' => 'The weapon shop', 'buys_weapons' => true, 'buys_armors' => false, 'buys_accessories' => false, 'buys_foods' => false, 'buys_jewels' => false, 'buys_dusts' => false, 'buys_others' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['rooms_id' => 85, 'name' => 'Armor Shop', 'description' => 'The armor shop', 'buys_weapons' => false, 'buys_armors' => true, 'buys_accessories' => false, 'buys_foods' => false, 'buys_jewels' => false, 'buys_dusts' => false, 'buys_others' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['rooms_id' => 58, 'name' => 'The Trinket Exchange', 'description' => 'The trinket shop', 'buys_weapons' => false, 'buys_armors' => false, 'buys_accessories' => true, 'buys_foods' => false, 'buys_jewels' => false, 'buys_dusts' => false, 'buys_others' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['rooms_id' => 24, 'name' => 'Food Shop', 'description' => 'The food shop', 'buys_weapons' => false, 'buys_armors' => false, 'buys_accessories' => false, 'buys_foods' => true, 'buys_jewels' => false, 'buys_dusts' => false, 'buys_others' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
		]);

		DB::table('traders')->insert([
			['rooms_id' => 79, 'name' => "Trader Jack's Exchange", 'description' => 'You walk in, and Trader Jack stands behind the counter, clothed in bear, deer and racoon <br>skins.  He smiles at you with a big grin.  A gold tooth glimmers at you as he asks,<br>"What can I do for you today?"<br><br>"Oh I should warn you, I can only hold 5 items for a player at a time."', 'trades_weapons' => true, 'trades_armors' => true, 'trades_accessories' => false, 'trades_foods' => false, 'trades_jewels' => false, 'trades_dusts' => false, 'trades_others' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['rooms_id' => 55, 'name' => 'Trader Bob', 'description' => 'Trader Bob', 'trades_weapons' => false, 'trades_armors' => false, 'trades_accessories' => true, 'trades_foods' => true, 'trades_jewels' => false, 'trades_dusts' => false, 'trades_others' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
		]);

		DB::table('shop_items')->insert([
			// Weapon shop:
			['shops_id' => 1, 'items_id' => 1, 'price' => null, 'markup' => 1.0, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['shops_id' => 1, 'items_id' => 2, 'price' => null, 'markup' => 1.0, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['shops_id' => 1, 'items_id' => 4, 'price' => null, 'markup' => 1.0, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['shops_id' => 1, 'items_id' => 6, 'price' => null, 'markup' => 1.0, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['shops_id' => 1, 'items_id' => 7, 'price' => null, 'markup' => 1.0, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['shops_id' => 1, 'items_id' => 8, 'price' => null, 'markup' => 1.0, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['shops_id' => 1, 'items_id' => 9, 'price' => null, 'markup' => 1.0, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['shops_id' => 1, 'items_id' => 10, 'price' => null, 'markup' => 1.0, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['shops_id' => 1, 'items_id' => 11, 'price' => null, 'markup' => 1.0, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['shops_id' => 1, 'items_id' => 35, 'price' => null, 'markup' => 1.0, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			// End Weapon
			['shops_id' => 2, 'items_id' => 61, 'price' => null, 'markup' => 1.0, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['shops_id' => 2, 'items_id' => 62, 'price' => null, 'markup' => 1.0, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['shops_id' => 2, 'items_id' => 63, 'price' => null, 'markup' => 1.0, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			// End 10
			['shops_id' => 2, 'items_id' => 64, 'price' => null, 'markup' => 1.0, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['shops_id' => 2, 'items_id' => 65, 'price' => null, 'markup' => 1.0, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['shops_id' => 2, 'items_id' => 66, 'price' => null, 'markup' => 1.0, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['shops_id' => 2, 'items_id' => 67, 'price' => null, 'markup' => 1.0, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['shops_id' => 2, 'items_id' => 68, 'price' => null, 'markup' => 1.0, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['shops_id' => 2, 'items_id' => 69, 'price' => null, 'markup' => 1.0, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['shops_id' => 2, 'items_id' => 70, 'price' => null, 'markup' => 1.0, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['shops_id' => 2, 'items_id' => 71, 'price' => null, 'markup' => 1.0, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['shops_id' => 2, 'items_id' => 72, 'price' => null, 'markup' => 1.0, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['shops_id' => 2, 'items_id' => 73, 'price' => null, 'markup' => 1.0, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			// End 20
			['shops_id' => 2, 'items_id' => 74, 'price' => null, 'markup' => 1.0, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			// Accessories
			['shops_id' => 3, 'items_id' => 118, 'price' => null, 'markup' => 1.0, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['shops_id' => 3, 'items_id' => 119, 'price' => null, 'markup' => 1.0, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['shops_id' => 3, 'items_id' => 120, 'price' => null, 'markup' => 1.0, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['shops_id' => 3, 'items_id' => 121, 'price' => null, 'markup' => 1.0, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['shops_id' => 3, 'items_id' => 122, 'price' => null, 'markup' => 1.0, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['shops_id' => 3, 'items_id' => 123, 'price' => null, 'markup' => 1.0, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			// remove later:
			['shops_id' => 3, 'items_id' => 129, 'price' => null, 'markup' => 1.0, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['shops_id' => 4, 'items_id' => 124, 'price' => null, 'markup' => 1.0, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
		]);

		// setup the room action:
		DB::table('room_actions')->insert([
			['uid' => 'sewer_cover', 'rooms_id' => 41, 'redirect_room' => null, 'description' => null, 'action' => 'lift', 'failed_action' => 'You are not strong enough to lift the cover!', 'success_action' => 'You succesfully lift the manhole cover, granting access to the Sewers!', 'display' => 'Try to [action] the manhole cover.', 'directions_blocked' => 'down', 'remember' => true, 'has_item' => null, 'completed_quest' => null, 'completed_quest_task' => null, 'strength_req' => 60, 'dexterity_req' => null, 'constitution_req' => null, 'wisdom_req' => null, 'intelligence_req' => null, 'charisma_req' => null, 'score_req' => null],
		]);
		}
	}
