<?php

use Illuminate\Database\Seeder;

class ItemsData extends Seeder
	{
		/**
		* Run the database seeds.
		*
		* @return void
		*/
		public function run()
		{
		DB::table('items')->insert([
			// Town weapons first:
			['name' => 'Knife', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Staff', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Desert Knife', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Sword', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Warrior knife', 'item_types_id' => 1, 'value' => 17400, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Staff of Eternity', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Gleaming Short Sword', 'item_types_id' => 1, 'value' => 18050, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Obsidian Wand', 'item_types_id' => 1, 'value' => 17200, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Pike', 'item_types_id' => 1, 'value' => 18650, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Katana', 'item_types_id' => 1, 'value' => 18650, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			// End 10
			['name' => 'Mace', 'item_types_id' => 1, 'value' => 17400, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Flaming Staff', 'item_types_id' => 1, 'value' => 16000, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Sword of Wailing', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'War Hammer', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Throwing Dagger', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Guard Sword', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Rubber Duckie', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Ogre Club', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Dwarven Hammer', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Elven Dagger', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			// End 20
			['name' => 'Emerald Orb', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Magi Staff', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Attack Rabbit', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Staff of the Desert Wind', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Elven Staff', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Morning Star', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Dwarven Axe', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Battle Axe', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Elven Sword', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Dagger of the Night', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			// End 30
			['name' => 'Shining Claw', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Double Ball Flail', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Jewelled Emerald Wand', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Bow of the Equinox', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Sword of Darkness', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Flaming Scimitar', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Elven Bow', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Jewelled Battle Axe', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Iron Baton', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Superior Jewelled Battle Axe', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			// End 40
			['name' => 'Fired Stiletto', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Claymore', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Air Crystal Bow', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Fire Ruby Axe', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Earth Obsidian Mace', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Aqua Sapphire Sword', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Flanged Mace', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Silver Throwing Daggers', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Ruby Mace', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Rod of Destiny', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			// End 50
			['name' => 'Triumphant Jewelled Battle Axe', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Tempered Kris', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Ultimate Jewelled Battle Axe', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Scepter of Alura Dhir', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Blackened Staff', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Frosted Saber', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Steel Banded Staff', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Ferrule of Reki Mia', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Sculped Dirk', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Giant War Axe', 'item_types_id' => 1, 'value' => 2500, 'weight' => 1, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			// End 60
			// End weapons:
			// Town armors:
			['name' => 'Leather Shield', 'item_types_id' => 2, 'value' => 3000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Leather Helm', 'item_types_id' => 2, 'value' => 3000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Leather Neckband', 'item_types_id' => 2, 'value' => 2500, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Leather Shirt', 'item_types_id' => 2, 'value' => 4500, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Leather Gloves', 'item_types_id' => 2, 'value' => 2000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Leather Pants', 'item_types_id' => 2, 'value' => 4000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Leather Boots', 'item_types_id' => 2, 'value' => 2500, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Wooden Shield', 'item_types_id' => 2, 'value' => 24000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Chain Mail Coif', 'item_types_id' => 2, 'value' => 24000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Chain Mail Neckband', 'item_types_id' => 2, 'value' => 20000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Chain Mail Shirt', 'item_types_id' => 2, 'value' => 72000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Chain Mail Gauntlets', 'item_types_id' => 2, 'value' => 16000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Chain Mail Leggings', 'item_types_id' => 2, 'value' => 32000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Chain Mail Boots', 'item_types_id' => 2, 'value' => 20000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Shimmering Cloak', 'item_types_id' => 2, 'value' => 20000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Silver Crested Shield', 'item_types_id' => 2, 'value' => 24000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Silver Chain Helm', 'item_types_id' => 2, 'value' => 24000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Silver Chain Neckband', 'item_types_id' => 2, 'value' => 20000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Silver Chain Mail', 'item_types_id' => 2, 'value' => 72000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Silver Chain Gauntlets', 'item_types_id' => 2, 'value' => 16000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Silver Chain Leggings', 'item_types_id' => 2, 'value' => 32000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Silver Chain Boots', 'item_types_id' => 2, 'value' => 20000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Emerald Fire Shield', 'item_types_id' => 2, 'value' => 24000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Gold Crown', 'item_types_id' => 2, 'value' => 24000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Green Scale Neckband', 'item_types_id' => 2, 'value' => 20000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Green Scale Mail', 'item_types_id' => 2, 'value' => 72000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Green Scale Gauntlets', 'item_types_id' => 2, 'value' => 16000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Green Scale Leggings', 'item_types_id' => 2, 'value' => 32000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Green Scale Boots', 'item_types_id' => 2, 'value' => 20000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Pearl Polished Shield', 'item_types_id' => 2, 'value' => 24000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Pearl Horned Crown', 'item_types_id' => 2, 'value' => 24000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Pearl Necklace', 'item_types_id' => 2, 'value' => 20000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Pearl Plate Mail', 'item_types_id' => 2, 'value' => 72000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Pearl Gauntlets', 'item_types_id' => 2, 'value' => 16000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Pearl Leggings', 'item_types_id' => 2, 'value' => 32000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Pearl Polished Boots', 'item_types_id' => 2, 'value' => 20000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Red Ruby Studded Shield', 'item_types_id' => 2, 'value' => 24000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Red Studded Helm', 'item_types_id' => 2, 'value' => 24000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Red Ruby Neckpiece', 'item_types_id' => 2, 'value' => 20000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Red Ruby Mail', 'item_types_id' => 2, 'value' => 72000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Red Ruby Gauntlets', 'item_types_id' => 2, 'value' => 16000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Red Ruby Leggings', 'item_types_id' => 2, 'value' => 32000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Red Ruby Slippers', 'item_types_id' => 2, 'value' => 20000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Aqua Sapphire Ancient Shield', 'item_types_id' => 2, 'value' => 24000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Aqua Sapphire Shell Visage', 'item_types_id' => 2, 'value' => 24000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Aqua Sapphire Necklace', 'item_types_id' => 2, 'value' => 20000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Aqua Sapphire Scarab Husk', 'item_types_id' => 2, 'value' => 72000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Aqua Sapphire Talon Gloves', 'item_types_id' => 2, 'value' => 16000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Aqua Sapphire Leggings', 'item_types_id' => 2, 'value' => 32000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Aqua Sapphire Boots', 'item_types_id' => 2, 'value' => 20000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Draconian Shield', 'item_types_id' => 2, 'value' => 24000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Dwarven Helm', 'item_types_id' => 2, 'value' => 24000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Halfling Necklace', 'item_types_id' => 2, 'value' => 20000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Elven Cloak', 'item_types_id' => 2, 'value' => 72000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Wraith Gloves', 'item_types_id' => 2, 'value' => 16000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Orcish Leggings', 'item_types_id' => 2, 'value' => 32000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Elven Boots', 'item_types_id' => 2, 'value' => 20000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			// End armors:
			['name' => 'Blue Amulet', 'item_types_id' => 3, 'value' => 10000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Black Amulet', 'item_types_id' => 3, 'value' => 37500000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Amulet of Apprentice', 'item_types_id' => 3, 'value' => 37500000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Glowing Ring', 'item_types_id' => 3, 'value' => 5000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Ring of Bone', 'item_types_id' => 3, 'value' => 5000000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Lightening Ring', 'item_types_id' => 3, 'value' => 5000000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			// Food real quick:
			['name' => 'Crab Legs', 'item_types_id' => 4, 'value' => 1, 'weight' => 0.25, 'is_stackable' => true, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => "Goat's Milk", 'item_types_id' => 4, 'value' => 1, 'weight' => 0.25, 'is_stackable' => true, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Whey Bread', 'item_types_id' => 4, 'value' => 1, 'weight' => 0.25, 'is_stackable' => true, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Ogre Pound Cake', 'item_types_id' => 4, 'value' => 1, 'weight' => 0.25, 'is_stackable' => true, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Peezza', 'item_types_id' => 4, 'value' => 1, 'weight' => 0.25, 'is_stackable' => true, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			// Forged, not bought:
			['name' => 'Green Bracelet', 'item_types_id' => 3, 'value' => 20000, 'weight' => 0.25, 'is_stackable' => false, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			
		]);

		DB::table('item_weapons')->insert([
			['items_id' => 1, 'weapon_types_id' => 3, 'equipment_slot' => 1, 'attack_text' => 'Your dagger does damage', 'damage_low' => 5, 'damage_high' => 13, 'fatigue_use' => 1.0, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 2, 'weapon_types_id' => 6, 'equipment_slot' => 1, 'attack_text' => 'You bash your opponent', 'damage_low' => 5, 'damage_high' => 13, 'fatigue_use' => 1.0, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 3, 'weapon_types_id' => 3, 'equipment_slot' => 1, 'attack_text' => 'You blade', 'damage_low' => 25, 'damage_high' => 5, 'fatigue_use' => 1.0, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 4, 'weapon_types_id' => 1, 'equipment_slot' => 1, 'attack_text' => 'You sword does damage', 'damage_low' => 10, 'damage_high' => 20, 'fatigue_use' => 1.0, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 5, 'weapon_types_id' => 3, 'equipment_slot' => 1, 'attack_text' => 'Your knife shivers as you wack your foe', 'damage_low' => 10, 'damage_high' => 25, 'fatigue_use' => 1.2, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 6, 'weapon_types_id' => 6, 'equipment_slot' => 1, 'attack_text' => 'A glimmering light radiates from your staff', 'damage_low' => 15, 'damage_high' => 30, 'fatigue_use' => 1.0, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 7, 'weapon_types_id' => 1, 'equipment_slot' => 1, 'attack_text' => 'Your sword fades in and out of view as it peels the flesh off your opponent', 'damage_low' => 15, 'damage_high' => 35, 'fatigue_use' => 1.0, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 8, 'weapon_types_id' => 7, 'equipment_slot' => 1, 'attack_text' => 'Small pebbles fly from the end of the wand', 'damage_low' => 24, 'damage_high' => 40, 'fatigue_use' => 1.0, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 9, 'weapon_types_id' => 3, 'equipment_slot' => 1, 'attack_text' => 'You pierce at your opponent', 'damage_low' => 30, 'damage_high' => 50, 'fatigue_use' => 1.2, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 10, 'weapon_types_id' => 1, 'equipment_slot' => 1, 'attack_text' => 'Your katana slices through flesh like water', 'damage_low' => 35, 'damage_high' => 50, 'fatigue_use' => 1.4, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 11, 'weapon_types_id' => 5, 'equipment_slot' => 1, 'attack_text' => 'You heave a huge weapon', 'damage_low' => 25, 'damage_high' => 55, 'fatigue_use' => 1.4, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 12, 'weapon_types_id' => 6, 'equipment_slot' => 1, 'attack_text' => 'Fire flows from your staff engulfing your enemy', 'damage_low' => 30, 'damage_high' => 60, 'fatigue_use' => 1.4, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 13, 'weapon_types_id' => 7, 'equipment_slot' => 1, 'attack_text' => 'A great banshee keen fills the air', 'damage_low' => 70, 'damage_high' => 150, 'fatigue_use' => 1.2, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 14, 'weapon_types_id' => 5, 'equipment_slot' => 1, 'attack_text' => 'You club your foe', 'damage_low' => 75, 'damage_high' => 175, 'fatigue_use' => 1.6, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 15, 'weapon_types_id' => 4, 'equipment_slot' => 1, 'attack_text' => 'You launch your dagger through the air', 'damage_low' => 90, 'damage_high' => 210, 'fatigue_use' => 1.0, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 16, 'weapon_types_id' => 1, 'equipment_slot' => 1, 'attack_text' => 'You swing your sword', 'damage_low' => 120, 'damage_high' => 280, 'fatigue_use' => 1.0, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 17, 'weapon_types_id' => 8, 'equipment_slot' => 1, 'attack_text' => 'You sqeak your Rubber Duckie at your foe', 'damage_low' => 120, 'damage_high' => 280, 'fatigue_use' => 1.0, 'accuracy' => 0.95, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 18, 'weapon_types_id' => 5, 'equipment_slot' => 1, 'attack_text' => 'You bash your foe with a dumb club', 'damage_low' => 200, 'damage_high' => 400, 'fatigue_use' => 1.6, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 19, 'weapon_types_id' => 5, 'equipment_slot' => 1, 'attack_text' => 'The Dwarven Hammer pounds its prey', 'damage_low' => 250, 'damage_high' => 250, 'fatigue_use' => 1.2, 'accuracy' => 0.8, 'crit_chance' => 0.1, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 20, 'weapon_types_id' => 3, 'equipment_slot' => 1, 'attack_text' => 'Your Elven Dagger slices and dices your enemy', 'damage_low' => 300, 'damage_high' => 600, 'fatigue_use' => 1.0, 'accuracy' => 0.8, 'crit_chance' => 0.1, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 21, 'weapon_types_id' => 7, 'equipment_slot' => 1, 'attack_text' => 'You hold the orb aloft and a great wind blows from within', 'damage_low' => 500, 'damage_high' => 1200, 'fatigue_use' => 1.2, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 22, 'weapon_types_id' => 6, 'equipment_slot' => 1, 'attack_text' => 'The skies turn dark as night as you raise the staff', 'damage_low' => 400, 'damage_high' => 1200, 'fatigue_use' => 1.8, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 23, 'weapon_types_id' => 8, 'equipment_slot' => 1, 'attack_text' => "The Rabbit attacks with it's big nasty pointy teeth", 'damage_low' => 300, 'damage_high' => 1500, 'fatigue_use' => 1.0, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 24, 'weapon_types_id' => 6, 'equipment_slot' => 1, 'attack_text' => 'A gust of wind tears at the flash', 'damage_low' => 725, 'damage_high' => 2350, 'fatigue_use' => 1.0, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 25, 'weapon_types_id' => 6, 'equipment_slot' => 1, 'attack_text' => 'You swing your staff with accuracy', 'damage_low' => 800, 'damage_high' => 1600, 'fatigue_use' => 1.0, 'accuracy' => 1.0, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 26, 'weapon_types_id' => 5, 'equipment_slot' => 1, 'attack_text' => 'You swing your morning star at the creature', 'damage_low' => 1200, 'damage_high' => 1900, 'fatigue_use' => 1.0, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 27, 'weapon_types_id' => 2, 'equipment_slot' => 1, 'attack_text' => 'You chop your enemies to bits', 'damage_low' => 1000, 'damage_high' => 2000, 'fatigue_use' => 1.0, 'accuracy' => 0.8, 'crit_chance' => 0.1, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 28, 'weapon_types_id' => 2, 'equipment_slot' => 1, 'attack_text' => 'Your mighty battle axe cleaves the foe', 'damage_low' => 1200, 'damage_high' => 2400, 'fatigue_use' => 1.8, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 29, 'weapon_types_id' => 1, 'equipment_slot' => 1, 'attack_text' => 'The Elvin blade slices through your enemy', 'damage_low' => 1500, 'damage_high' => 2500, 'fatigue_use' => 1.0, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 30, 'weapon_types_id' => 3, 'equipment_slot' => 1, 'attack_text' => 'Your dagger slices through the night', 'damage_low' => 2000, 'damage_high' => 2750, 'fatigue_use' => 1.0, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 31, 'weapon_types_id' => 7, 'equipment_slot' => 1, 'attack_text' => 'The claw emits a thin beam of light', 'damage_low' => 1800, 'damage_high' => 2600, 'fatigue_use' => 1.2, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 32, 'weapon_types_id' => 5, 'equipment_slot' => 1, 'attack_text' => 'The dual heads of your flailt swing towards your enemy', 'damage_low' => 2100, 'damage_high' => 2750, 'fatigue_use' => 1.5, 'accuracy' => 0.95, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 33, 'weapon_types_id' => 6, 'equipment_slot' => 1, 'attack_text' => 'Glittery dust embalms the creature', 'damage_low' => 2000, 'damage_high' => 3000, 'fatigue_use' => 1.0, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 34, 'weapon_types_id' => 4, 'equipment_slot' => 1, 'attack_text' => 'Your arrow strikes the creature', 'damage_low' => 2000, 'damage_high' => 3500, 'fatigue_use' => 1.0, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 35, 'weapon_types_id' => 1, 'equipment_slot' => 1, 'attack_text' => 'Darkness envelopes the creature', 'damage_low' => 2500, 'damage_high' => 3500, 'fatigue_use' => 1.0, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 36, 'weapon_types_id' => 1, 'equipment_slot' => 1, 'attack_text' => 'Flames burns the flesh of the creature', 'damage_low' => 3000, 'damage_high' => 4000, 'fatigue_use' => 1.0, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 37, 'weapon_types_id' => 4, 'equipment_slot' => 1, 'attack_text' => 'With swiftness and accuracy you shoot your arrows', 'damage_low' => 3000, 'damage_high' => 4000, 'fatigue_use' => 1.0, 'accuracy' => 1.0, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 38, 'weapon_types_id' => 2, 'equipment_slot' => 1, 'attack_text' => 'Your mighty jewelled battle axe cleaves the foe', 'damage_low' => 3000, 'damage_high' => 4500, 'fatigue_use' => 1.0, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 39, 'weapon_types_id' => 7, 'equipment_slot' => 1, 'attack_text' => 'Lightning bolts fly from the baton and strike your foe', 'damage_low' => 5, 'damage_high' => 13, 'fatigue_use' => 1.2, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 40, 'weapon_types_id' => 2, 'equipment_slot' => 1, 'attack_text' => 'Your mighty jewelled battle axe cleaves the foe', 'damage_low' => 4000, 'damage_high' => 5500, 'fatigue_use' => 1.5, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 41, 'weapon_types_id' => 3, 'equipment_slot' => 1, 'attack_text' => 'Your stiletto slides into flesh', 'damage_low' => 4400, 'damage_high' => 5100, 'fatigue_use' => 1.5, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 42, 'weapon_types_id' => 1, 'equipment_slot' => 1, 'attack_text' => "You swing your heavy claymore, blasting through the creature's armor", 'damage_low' => 4700, 'damage_high' => 5200, 'fatigue_use' => 1.5, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 43, 'weapon_types_id' => 4, 'equipment_slot' => 1, 'attack_text' => 'The power of the air engulfs the creature', 'damage_low' => 4500, 'damage_high' => 5500, 'fatigue_use' => 1.0, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 44, 'weapon_types_id' => 2, 'equipment_slot' => 1, 'attack_text' => 'The power of the fire engulfs the creature', 'damage_low' => 4500, 'damage_high' => 5500, 'fatigue_use' => 1.0, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 45, 'weapon_types_id' => 5, 'equipment_slot' => 1, 'attack_text' => 'The power of the ground engulfs the creature', 'damage_low' => 4500, 'damage_high' => 5500, 'fatigue_use' => 1.0, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 46, 'weapon_types_id' => 1, 'equipment_slot' => 1, 'attack_text' => 'The power of the water engulfs the creature', 'damage_low' => 5, 'damage_high' => 13, 'fatigue_use' => 1.0, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 47, 'weapon_types_id' => 5, 'equipment_slot' => 1, 'attack_text' => 'The flanges glow with an inner light', 'damage_low' => 5000, 'damage_high' => 5500, 'fatigue_use' => 1.2, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 48, 'weapon_types_id' => 4, 'equipment_slot' => 1, 'attack_text' => 'Your silvery daggers tumble through the air', 'damage_low' => 5000, 'damage_high' => 6000, 'fatigue_use' => 1.0, 'accuracy' => 0.95, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 49, 'weapon_types_id' => 7, 'equipment_slot' => 1, 'attack_text' => 'A stream of lava issues from your mace', 'damage_low' => 5200, 'damage_high' => 6000, 'fatigue_use' => 1.2, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 50, 'weapon_types_id' => 6, 'equipment_slot' => 1, 'attack_text' => 'Destiny binds the creature', 'damage_low' => 5500, 'damage_high' => 6500, 'fatigue_use' => 1.0, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 51, 'weapon_types_id' => 2, 'equipment_slot' => 1, 'attack_text' => 'Your mighty jewelled battle axe cleaves the foe', 'damage_low' => 5500, 'damage_high' => 6500, 'fatigue_use' => 1.8, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 52, 'weapon_types_id' => 3, 'equipment_slot' => 1, 'attack_text' => 'The kris ripes a jagged wound', 'damage_low' => 5700, 'damage_high' => 7100, 'fatigue_use' => 1.2, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 53, 'weapon_types_id' => 2, 'equipment_slot' => 1, 'attack_text' => 'Your mighty jewelled battle axe cleaves the foe', 'damage_low' => 6500, 'damage_high' => 7500, 'fatigue_use' => 1.8, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 54, 'weapon_types_id' => 5, 'equipment_slot' => 1, 'attack_text' => 'The mystic scepter unleashes its unnatural power', 'damage_low' => 5500, 'damage_high' => 6500, 'fatigue_use' => 1.0, 'accuracy' => 0.95, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 55, 'weapon_types_id' => 7, 'equipment_slot' => 1, 'attack_text' => 'YHou level the staff and send black bolts at your foe', 'damage_low' => 6300, 'damage_high' => 7500, 'fatigue_use' => 1.2, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 56, 'weapon_types_id' => 1, 'equipment_slot' => 1, 'attack_text' => 'The saber chills the air and slashes your enemy', 'damage_low' => 6500, 'damage_high' => 7100, 'fatigue_use' => 1.0, 'accuracy' => 0.8, 'crit_chance' => 0.1, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 57, 'weapon_types_id' => 6, 'equipment_slot' => 1, 'attack_text' => 'The steel bands flash in the light as you swing your staff', 'damage_low' => 7000, 'damage_high' => 7750, 'fatigue_use' => 1.6, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 58, 'weapon_types_id' => 7, 'equipment_slot' => 1, 'attack_text' => 'A shower of colorful sparks shot forth', 'damage_low' => 7500, 'damage_high' => 8500, 'fatigue_use' => 1.0, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 59, 'weapon_types_id' => 3, 'equipment_slot' => 1, 'attack_text' => "Your quick thrust penetrates your foe's armor", 'damage_low' => 7550, 'damage_high' => 8550, 'fatigue_use' => 1.0, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 60, 'weapon_types_id' => 2, 'equipment_slot' => 1, 'attack_text' => 'Your war axe streaks toward your foe', 'damage_low' => 7800, 'damage_high' => 8800, 'fatigue_use' => 1.8, 'accuracy' => 0.8, 'crit_chance' => 0.0, 'required_stat' => null, 'required_amount' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
		]);

		DB::table('item_armors')->insert([
			['items_id' => 61, 'equipment_slot' => 2, 'armor' => 3, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 62, 'equipment_slot' => 3, 'armor' => 3, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 63, 'equipment_slot' => 4, 'armor' => 3, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 64, 'equipment_slot' => 5, 'armor' => 3, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 65, 'equipment_slot' => 6, 'armor' => 3, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 66, 'equipment_slot' => 7, 'armor' => 3, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 67, 'equipment_slot' => 8, 'armor' => 3, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 68, 'equipment_slot' => 2, 'armor' => 6, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 69, 'equipment_slot' => 3, 'armor' => 6, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 70, 'equipment_slot' => 4, 'armor' => 6, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 71, 'equipment_slot' => 5, 'armor' => 6, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 72, 'equipment_slot' => 6, 'armor' => 6, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 73, 'equipment_slot' => 7, 'armor' => 6, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 74, 'equipment_slot' => 8, 'armor' => 6, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 75, 'equipment_slot' => 5, 'armor' => 9, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 76, 'equipment_slot' => 2, 'armor' => 9, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 77, 'equipment_slot' => 3, 'armor' => 9, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 78, 'equipment_slot' => 4, 'armor' => 9, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 79, 'equipment_slot' => 5, 'armor' => 9, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 80, 'equipment_slot' => 6, 'armor' => 9, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 81, 'equipment_slot' => 7, 'armor' => 9, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 82, 'equipment_slot' => 8, 'armor' => 9, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 83, 'equipment_slot' => 2, 'armor' => 12, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 84, 'equipment_slot' => 3, 'armor' => 12, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 85, 'equipment_slot' => 4, 'armor' => 12, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 86, 'equipment_slot' => 5, 'armor' => 12, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 87, 'equipment_slot' => 6, 'armor' => 12, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 88, 'equipment_slot' => 7, 'armor' => 12, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 89, 'equipment_slot' => 8, 'armor' => 12, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 90, 'equipment_slot' => 2, 'armor' => 15, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 91, 'equipment_slot' => 3, 'armor' => 15, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 92, 'equipment_slot' => 4, 'armor' => 15, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 93, 'equipment_slot' => 5, 'armor' => 15, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 94, 'equipment_slot' => 6, 'armor' => 15, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 95, 'equipment_slot' => 7, 'armor' => 15, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 96, 'equipment_slot' => 8, 'armor' => 15, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 97, 'equipment_slot' => 2, 'armor' => 18, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 98, 'equipment_slot' => 3, 'armor' => 18, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 99, 'equipment_slot' => 4, 'armor' => 18, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 100, 'equipment_slot' => 5, 'armor' => 18, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 101, 'equipment_slot' => 6, 'armor' => 18, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 102, 'equipment_slot' => 7, 'armor' => 18, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 103, 'equipment_slot' => 8, 'armor' => 18, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 104, 'equipment_slot' => 2, 'armor' => 21, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 105, 'equipment_slot' => 3, 'armor' => 21, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 106, 'equipment_slot' => 4, 'armor' => 21, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 107, 'equipment_slot' => 5, 'armor' => 21, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 108, 'equipment_slot' => 6, 'armor' => 21, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 109, 'equipment_slot' => 7, 'armor' => 21, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 110, 'equipment_slot' => 8, 'armor' => 21, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 111, 'equipment_slot' => 2, 'armor' => 27, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 112, 'equipment_slot' => 3, 'armor' => 27, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 113, 'equipment_slot' => 4, 'armor' => 27, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 114, 'equipment_slot' => 5, 'armor' => 27, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 115, 'equipment_slot' => 6, 'armor' => 27, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 116, 'equipment_slot' => 7, 'armor' => 27, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 117, 'equipment_slot' => 8, 'armor' => 27, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],

		]);

		DB::table('item_accessories')->insert([
			['items_id' => 118, 'equipment_slot' => 9, 'light_level' => null, 'strength_bonus' => 10, 'dexterity_bonus' => null, 'constitution_bonus' => null, 'wisdom_bonus' => null, 'intelligence_bonus' => null, 'charisma_bonus' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 119, 'equipment_slot' => 9, 'light_level' => null, 'strength_bonus' => 50, 'dexterity_bonus' => null, 'constitution_bonus' => null, 'wisdom_bonus' => null, 'intelligence_bonus' => null, 'charisma_bonus' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 120, 'equipment_slot' => 9, 'light_level' => null, 'strength_bonus' => null, 'dexterity_bonus' => null, 'constitution_bonus' => null, 'wisdom_bonus' => 50, 'intelligence_bonus' => null, 'charisma_bonus' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 121, 'equipment_slot' => 10, 'light_level' => null, 'strength_bonus' => 5, 'dexterity_bonus' => null, 'constitution_bonus' => null, 'wisdom_bonus' => null, 'intelligence_bonus' => null, 'charisma_bonus' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 122, 'equipment_slot' => 10, 'light_level' => null, 'strength_bonus' => null, 'dexterity_bonus' => null, 'constitution_bonus' => null, 'wisdom_bonus' => null, 'intelligence_bonus' => 25, 'charisma_bonus' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 123, 'equipment_slot' => 10, 'light_level' => 1, 'strength_bonus' => null, 'dexterity_bonus' => 20, 'constitution_bonus' => null, 'wisdom_bonus' => null, 'intelligence_bonus' => null, 'charisma_bonus' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 129, 'equipment_slot' => 11, 'light_level' => null, 'strength_bonus' => 20, 'dexterity_bonus' => 20, 'constitution_bonus' => null, 'wisdom_bonus' => 20, 'intelligence_bonus' => null, 'charisma_bonus' => 20, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
		]);

		DB::table('item_foods')->insert([
			['items_id' => 124, 'potency' => 9, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 125, 'potency' => 18, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 126, 'potency' => 27, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 127, 'potency' => 36, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['items_id' => 127, 'potency' => 45, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
		]);
		}
	}
