<?php

use Illuminate\Database\Seeder;

class ZoneData extends Seeder
	{
		/**
		* Run the database seeds.
		*
		* @return void
		*/
		public function run()
		{
		//Beach
		DB::table('rooms')->insert([
			[ 'zones_id' => 2, 'uid' => null, 'title' => 'Builder Starting Point', 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 19, 'east_rooms_id' => 94, 'south_rooms_id' => 95, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => 96, 'west_rooms_id' => 93, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 93, 'east_rooms_id' => 96, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 94, 'east_rooms_id' => 99, 'south_rooms_id' => 97, 'west_rooms_id' => 95, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 96, 'east_rooms_id' => 98, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 99, 'east_rooms_id' => 101, 'south_rooms_id' => 103, 'west_rooms_id' => 97, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 100, 'south_rooms_id' => 98, 'west_rooms_id' => 96, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => 101, 'west_rooms_id' => 99, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 100, 'east_rooms_id' => null, 'south_rooms_id' => 102, 'west_rooms_id' => 98, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 101, 'east_rooms_id' => null, 'south_rooms_id' => 104, 'west_rooms_id' => 103, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 98, 'east_rooms_id' => 102, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 102, 'east_rooms_id' => 105, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 107, 'south_rooms_id' => 106, 'west_rooms_id' => 104, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 105, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 108, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => 105, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => 'beach_tele2', 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 109, 'south_rooms_id' => 107, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 110, 'east_rooms_id' => 111, 'south_rooms_id' => null, 'west_rooms_id' => 108, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => 109, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 112, 'south_rooms_id' => null, 'west_rooms_id' => 109, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 114, 'east_rooms_id' => 117, 'south_rooms_id' => 113, 'west_rooms_id' => 111, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 112, 'east_rooms_id' => 116, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 115, 'east_rooms_id' => 118, 'south_rooms_id' => 112, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 119, 'south_rooms_id' => 114, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 117, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => 113, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 118, 'east_rooms_id' => 120, 'south_rooms_id' => 116, 'west_rooms_id' => 112, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 119, 'east_rooms_id' => 121, 'south_rooms_id' => 117, 'west_rooms_id' => 114, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 122, 'south_rooms_id' => 118, 'west_rooms_id' => 115, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 121, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => 117, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 122, 'east_rooms_id' => 124, 'south_rooms_id' => 120, 'west_rooms_id' => 118, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 123, 'east_rooms_id' => 125, 'south_rooms_id' => 121, 'west_rooms_id' => 119, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 126, 'south_rooms_id' => 122, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 125, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => 121, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 126, 'east_rooms_id' => 128, 'south_rooms_id' => 124, 'west_rooms_id' => 122, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 127, 'east_rooms_id' => null, 'south_rooms_id' => 125, 'west_rooms_id' => 123, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => 'beach_tele3', 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => 126, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => 'mermaid_hunter', 'title' => 'Damp Cave', 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => 125, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			]);
		// Link to existing Beach rooms:
		DB::table('rooms')->updateOrInsert(['id' => 19], ['south_rooms_id' => 93]);

		// Outskirts:
		DB::table('rooms')->insert([
			[ 'zones_id' => 3, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => 130, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => 21, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 129, 'south_rooms_id' => null, 'west_rooms_id' => 131, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 130, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => 132, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => 131, 'southwest_rooms_id' => null, 'northwest_rooms_id' => 133, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 134, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => 132, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 135, 'east_rooms_id' => null, 'south_rooms_id' => 133, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 136, 'east_rooms_id' => null, 'south_rooms_id' => 134, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => 135, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => 137, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 138, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => 136, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 139, 'south_rooms_id' => null, 'west_rooms_id' => 137, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => 138, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => 140, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 141, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => 139, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 142, 'east_rooms_id' => null, 'south_rooms_id' => 140, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 143, 'east_rooms_id' => null, 'south_rooms_id' => 141, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => 142, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => 146, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => 144, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => 143, 'southwest_rooms_id' => null, 'northwest_rooms_id' => 145, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => 149, 'southeast_rooms_id' => 144, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => 147, 'southeast_rooms_id' => null, 'southwest_rooms_id' => 143, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => 146, 'northwest_rooms_id' => 148, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => 147, 'southwest_rooms_id' => null, 'northwest_rooms_id' => 150, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => 150, 'southeast_rooms_id' => null, 'southwest_rooms_id' => 145, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 151, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => 148, 'southwest_rooms_id' => 149, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 152, 'east_rooms_id' => null, 'south_rooms_id' => 150, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => 151, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			]);
		DB::table('rooms')->updateOrInsert(['id' => 21], ['northwest_rooms_id' => 129]);

		// Sewers:
		DB::table('rooms')->insert([
			[ 'zones_id' => 4, 'uid' => 'sewers_entrance', 'title' => 'Sewers Entrance', 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 158, 'east_rooms_id' => 156, 'south_rooms_id' => 154, 'west_rooms_id' => 160, 'up_rooms_id' => 48, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 153, 'east_rooms_id' => 155, 'south_rooms_id' => 163, 'west_rooms_id' => 161, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 156, 'east_rooms_id' => 166, 'south_rooms_id' => 164, 'west_rooms_id' => 154, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 157, 'east_rooms_id' => 167, 'south_rooms_id' => 155, 'west_rooms_id' => 153, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 170, 'east_rooms_id' => 168, 'south_rooms_id' => 156, 'west_rooms_id' => 158, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 171, 'east_rooms_id' => 157, 'south_rooms_id' => 153, 'west_rooms_id' => 159, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 172, 'east_rooms_id' => 158, 'south_rooms_id' => 160, 'west_rooms_id' => 174, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 159, 'east_rooms_id' => 153, 'south_rooms_id' => 161, 'west_rooms_id' => 175, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 160, 'east_rooms_id' => 154, 'south_rooms_id' => 162, 'west_rooms_id' => 176, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 161, 'east_rooms_id' => 163, 'south_rooms_id' => null, 'west_rooms_id' => 177, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 154, 'east_rooms_id' => 164, 'south_rooms_id' => null, 'west_rooms_id' => 162, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 155, 'east_rooms_id' => 165, 'south_rooms_id' => null, 'west_rooms_id' => 163, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 166, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => 164, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 167, 'east_rooms_id' => null, 'south_rooms_id' => 165, 'west_rooms_id' => 155, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 168, 'east_rooms_id' => null, 'south_rooms_id' => 166, 'west_rooms_id' => 156, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 169, 'east_rooms_id' => null, 'south_rooms_id' => 167, 'west_rooms_id' => 157, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => 168, 'west_rooms_id' => 170, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 169, 'south_rooms_id' => 157, 'west_rooms_id' => 171, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 170, 'south_rooms_id' => 158, 'west_rooms_id' => 172, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 171, 'south_rooms_id' => 159, 'west_rooms_id' => 173, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 172, 'south_rooms_id' => 174, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 173, 'east_rooms_id' => 159, 'south_rooms_id' => 175, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 174, 'east_rooms_id' => 160, 'south_rooms_id' => 176, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 175, 'east_rooms_id' => 161, 'south_rooms_id' => 177, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 176, 'east_rooms_id' => 162, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ]
			]);
		DB::table('rooms')->updateOrInsert(['id' => 48], ['down_rooms_id' => 153]);
		}
	}