<?php

use Illuminate\Database\Seeder;

class ZoneData extends Seeder
	{
		/**
		* Run the database seeds.
		*
		* @return void
		*/
		public function run()
		{
		DB::table('rooms')->insert([
			[ 'zones_id' => 2, 'uid' => null, 'title' => 'Builder Starting Point', 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 19, 'east_rooms_id' => 94, 'south_rooms_id' => 95, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => 96, 'west_rooms_id' => 93, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 93, 'east_rooms_id' => 96, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 94, 'east_rooms_id' => 99, 'south_rooms_id' => 97, 'west_rooms_id' => 95, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 96, 'east_rooms_id' => 98, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 99, 'east_rooms_id' => 101, 'south_rooms_id' => 103, 'west_rooms_id' => 97, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 100, 'south_rooms_id' => 98, 'west_rooms_id' => 96, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => 101, 'west_rooms_id' => 99, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 100, 'east_rooms_id' => null, 'south_rooms_id' => 102, 'west_rooms_id' => 98, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 101, 'east_rooms_id' => null, 'south_rooms_id' => 104, 'west_rooms_id' => 103, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 98, 'east_rooms_id' => 102, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 102, 'east_rooms_id' => 105, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 107, 'south_rooms_id' => 106, 'west_rooms_id' => 104, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 105, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 108, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => 105, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => 'beach_tele2', 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 109, 'south_rooms_id' => 107, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 110, 'east_rooms_id' => 111, 'south_rooms_id' => null, 'west_rooms_id' => 108, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => 109, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 112, 'south_rooms_id' => null, 'west_rooms_id' => 109, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 114, 'east_rooms_id' => 117, 'south_rooms_id' => 113, 'west_rooms_id' => 111, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 112, 'east_rooms_id' => 116, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 115, 'east_rooms_id' => 118, 'south_rooms_id' => 112, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 119, 'south_rooms_id' => 114, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 117, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => 113, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 118, 'east_rooms_id' => 120, 'south_rooms_id' => 116, 'west_rooms_id' => 112, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 119, 'east_rooms_id' => 121, 'south_rooms_id' => 117, 'west_rooms_id' => 114, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 122, 'south_rooms_id' => 118, 'west_rooms_id' => 115, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 121, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => 117, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 122, 'east_rooms_id' => 124, 'south_rooms_id' => 120, 'west_rooms_id' => 118, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 123, 'east_rooms_id' => 125, 'south_rooms_id' => 121, 'west_rooms_id' => 119, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 126, 'south_rooms_id' => 122, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 125, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => 121, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 126, 'east_rooms_id' => 128, 'south_rooms_id' => 124, 'west_rooms_id' => 122, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 127, 'east_rooms_id' => null, 'south_rooms_id' => 125, 'west_rooms_id' => 123, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => 'beach_tele3', 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => 126, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'uid' => 'mermaid_hunter', 'title' => 'Damp Cave', 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => 125, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			]);

		DB::table('rooms')->updateOrInsert(['id' => 19], ['south_rooims_id' => 93]);
		}
	}