<?php

use Illuminate\Database\Seeder;

class ZoneData extends Seeder
	{
		/**
		* Run the database seeds.
		*
		* @return void
		*/
		public function run()
		{
		// Zones
		DB::table('zones')->insert([
<<<<<<< HEAD
			['name' => 'Beach', 'description' => '', 'travel_text' => 'You are standing on a sandy beach.', 'bg_color' => null, 'img_src' => 'beach.gif', 'font_color' => null, 'label_color' => null, 'custom_view' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Outskirts', 'description' => '', 'travel_text' => 'You are standing in the Outskirts.', 'bg_color' => null, 'img_src' => 'beach.gif', 'font_color' => null, 'label_color' => null, 'custom_view' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Sewers', 'description' => '', 'travel_text' => 'You are standing in the dismal sewers.', 'bg_color' => null, 'img_src' => 'beach.gif', 'font_color' => null, 'label_color' => null, 'custom_view' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
=======
			['name' => 'Beach', 'description' => '', 'travel_text' => 'You are standing on a sandy beach.', 'img_src' => 'beach.gif', 'bg_color' => null, 'font_color' => null, 'label_color' => null, 'custom_view' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Outskirts', 'description' => '', 'travel_text' => 'You are standing in the Outskirts.', 'img_src' => null, 'bg_color' => null, 'font_color' => null, 'label_color' => null, 'custom_view' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['name' => 'Sewers', 'description' => '', 'travel_text' => 'You are standing in the dismal sewers.', 'img_src' => null, 'bg_color' => null, 'font_color' => null, 'label_color' => null, 'custom_view' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
>>>>>>> 7734c044c96ea8ad305109a118d71b47da9a873a
			]);

		DB::table('zone_to_zone_properties')->insert([
			['zones_id' => 3, 'zone_properties_id' => 1, 'data' => '{"intelligence":40}', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 4, 'zone_properties_id' => 8, 'data' => '{"level":1}', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			]);

		DB::table('zone_levels')->insert([
			['zones_id' => 2, 'level' => 0, 'name' => null, 'inherit_creatures' => true, 'inherit_properties' => true, 'description' => '', 'img_src' => null, 'bg_color' => null, 'font_color' => null, 'label_color' => null, 'custom_view' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 3, 'level' => 0, 'name' => null, 'inherit_creatures' => true, 'inherit_properties' => true, 'description' => '', 'img_src' => null, 'bg_color' => null, 'font_color' => null, 'label_color' => null, 'custom_view' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['zones_id' => 4, 'level' => 0, 'name' => null, 'inherit_creatures' => true, 'inherit_properties' => true, 'description' => '', 'img_src' => null, 'bg_color' => null, 'font_color' => null, 'label_color' => null, 'custom_view' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
		]);

		//Beach
		DB::table('rooms')->insert([
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => 'TP 1 - Beach Entrance', 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 8, 'east_rooms_id' => null, 'south_rooms_id' => 88, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 87, 'east_rooms_id' => null, 'south_rooms_id' => 89, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 88, 'east_rooms_id' => 90, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => 92, 'west_rooms_id' => 89, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => 'TP 3 - Exit East to Sand Mansion', 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => 95, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 90, 'east_rooms_id' => 93, 'south_rooms_id' => 96, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => 97, 'west_rooms_id' => 92, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 95, 'south_rooms_id' => 102, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 91, 'east_rooms_id' => null, 'south_rooms_id' => 103, 'west_rooms_id' => 94, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 92, 'east_rooms_id' => 97, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 93, 'east_rooms_id' => 98, 'south_rooms_id' => 105, 'west_rooms_id' => 96, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 99, 'south_rooms_id' => 106, 'west_rooms_id' => 97, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => 107, 'west_rooms_id' => 98, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 101, 'south_rooms_id' => 109, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 102, 'south_rooms_id' => 110, 'west_rooms_id' => 100, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 94, 'east_rooms_id' => 103, 'south_rooms_id' => 111, 'west_rooms_id' => 101, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 95, 'east_rooms_id' => 104, 'south_rooms_id' => 112, 'west_rooms_id' => 102, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => 'Mermaid Hunter', 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => 103, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 97, 'east_rooms_id' => 106, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 98, 'east_rooms_id' => 107, 'south_rooms_id' => 113, 'west_rooms_id' => 105, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 99, 'east_rooms_id' => null, 'south_rooms_id' => 114, 'west_rooms_id' => 106, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => 116, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 100, 'east_rooms_id' => 110, 'south_rooms_id' => 118, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 101, 'east_rooms_id' => 111, 'south_rooms_id' => 119, 'west_rooms_id' => 109, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 102, 'east_rooms_id' => 112, 'south_rooms_id' => 120, 'west_rooms_id' => 110, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 103, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => 111, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 106, 'east_rooms_id' => 114, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 107, 'east_rooms_id' => null, 'south_rooms_id' => 121, 'west_rooms_id' => 113, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => 'TP 2', 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 116, 'south_rooms_id' => 123, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 108, 'east_rooms_id' => 117, 'south_rooms_id' => null, 'west_rooms_id' => 115, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 118, 'south_rooms_id' => null, 'west_rooms_id' => 116, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 109, 'east_rooms_id' => 119, 'south_rooms_id' => 124, 'west_rooms_id' => 117, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 110, 'east_rooms_id' => 120, 'south_rooms_id' => 125, 'west_rooms_id' => 118, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 111, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => 119, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 114, 'east_rooms_id' => 122, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 123, 'south_rooms_id' => 126, 'west_rooms_id' => 121, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 115, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => 122, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 118, 'east_rooms_id' => 125, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 119, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => 124, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 2, 'zone_level' => 0, 'uid' => null, 'title' => 'Exit East to Ocean', 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 122, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			]);
		// Link Town:
		DB::table('rooms')->updateOrInsert(['id' => 8], ['south_rooms_id' => 87]);
		

		
		// Outskirts:
		DB::table('rooms')->insert([
			[ 'zones_id' => 3, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => 128, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 127, 'east_rooms_id' => null, 'south_rooms_id' => 129, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 128, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => 131, 'southwest_rooms_id' => 130, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => 129, 'southeast_rooms_id' => null, 'southwest_rooms_id' => 132, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => 133, 'southwest_rooms_id' => null, 'northwest_rooms_id' => 129, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => 130, 'southeast_rooms_id' => 134, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => 135, 'northwest_rooms_id' => 131, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => 136, 'southwest_rooms_id' => null, 'northwest_rooms_id' => 132, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => 133, 'southeast_rooms_id' => null, 'southwest_rooms_id' => 136, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => 137, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => 135, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => 134, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 136, 'east_rooms_id' => null, 'south_rooms_id' => 138, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 137, 'east_rooms_id' => null, 'south_rooms_id' => 139, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'zone_level' => 0, 'uid' => null, 'title' => 'TP 1 - SE to Gala', 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 138, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => 142, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 141, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => 143, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 142, 'south_rooms_id' => null, 'west_rooms_id' => 140, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => 141, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => 139, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => 144, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => 140, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 143, 'east_rooms_id' => null, 'south_rooms_id' => 145, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 144, 'east_rooms_id' => null, 'south_rooms_id' => 146, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 145, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => 147, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => 148, 'southwest_rooms_id' => null, 'northwest_rooms_id' => 146, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 149, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => 147, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 150, 'south_rooms_id' => null, 'west_rooms_id' => 148, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => 149, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => 151, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => 152, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => 150, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 151, 'east_rooms_id' => null, 'south_rooms_id' => 153, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 3, 'zone_level' => 0, 'uid' => null, 'title' => 'South to Shillatown', 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 152, 'east_rooms_id' => null, 'south_rooms_id' => 14, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			]);
		// Link Town:
		DB::table('rooms')->updateOrInsert(['id' => 14], ['north_rooms_id' => 153]);

		// Sewers:
		DB::table('rooms')->insert([
			[ 'zones_id' => 4, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 155, 'south_rooms_id' => 159, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 156, 'south_rooms_id' => 160, 'west_rooms_id' => 154, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 157, 'south_rooms_id' => 161, 'west_rooms_id' => 155, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => 158, 'south_rooms_id' => 162, 'west_rooms_id' => 156, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => 163, 'west_rooms_id' => 157, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 154, 'east_rooms_id' => 160, 'south_rooms_id' => 164, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 155, 'east_rooms_id' => 161, 'south_rooms_id' => 165, 'west_rooms_id' => 159, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 156, 'east_rooms_id' => 162, 'south_rooms_id' => 166, 'west_rooms_id' => 160, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 157, 'east_rooms_id' => 163, 'south_rooms_id' => 167, 'west_rooms_id' => 161, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 158, 'east_rooms_id' => null, 'south_rooms_id' => 168, 'west_rooms_id' => 162, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 159, 'east_rooms_id' => 165, 'south_rooms_id' => 169, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 160, 'east_rooms_id' => 166, 'south_rooms_id' => 170, 'west_rooms_id' => 164, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 161, 'east_rooms_id' => 167, 'south_rooms_id' => 171, 'west_rooms_id' => 165, 'up_rooms_id' => 41, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 162, 'east_rooms_id' => 168, 'south_rooms_id' => 173, 'west_rooms_id' => 166, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 163, 'east_rooms_id' => null, 'south_rooms_id' => 174, 'west_rooms_id' => 167, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 164, 'east_rooms_id' => 170, 'south_rooms_id' => 175, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 165, 'east_rooms_id' => 171, 'south_rooms_id' => 176, 'west_rooms_id' => 169, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 166, 'east_rooms_id' => 173, 'south_rooms_id' => 177, 'west_rooms_id' => 170, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => null, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 167, 'east_rooms_id' => 174, 'south_rooms_id' => 178, 'west_rooms_id' => 171, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 168, 'east_rooms_id' => null, 'south_rooms_id' => 179, 'west_rooms_id' => 173, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 169, 'east_rooms_id' => 176, 'south_rooms_id' => null, 'west_rooms_id' => null, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 170, 'east_rooms_id' => 177, 'south_rooms_id' => null, 'west_rooms_id' => 175, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 171, 'east_rooms_id' => 178, 'south_rooms_id' => null, 'west_rooms_id' => 176, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 173, 'east_rooms_id' => 179, 'south_rooms_id' => null, 'west_rooms_id' => 177, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			[ 'zones_id' => 4, 'zone_level' => 0, 'uid' => null, 'title' => null, 'description' => null, 'darkness_level' => null, 'img_src' => null, 'spawns_enabled' => true, 'north_rooms_id' => 174, 'east_rooms_id' => null, 'south_rooms_id' => null, 'west_rooms_id' => 178, 'up_rooms_id' => null, 'down_rooms_id' => null, 'northeast_rooms_id' => null, 'southeast_rooms_id' => null, 'southwest_rooms_id' => null, 'northwest_rooms_id' => null, 'room_properties_id' => null, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ],
			]);
		// Link Town:
		DB::table('rooms')->updateOrInsert(['id' => 41], ['down_rooms_id' => 166]);
		}
	}